"""
Additional data sources to reach 100+ registered endpoints (Buyer Requirement #8).
Only unique source_ids not already in data_sources_registry.py.
"""

from __future__ import annotations

from data_sources_registry import DataSourceSpec

EXTRA_DATA_SOURCES: tuple[DataSourceSpec, ...] = (
    DataSourceSpec("gateio_futures", "prices", "Gate.io Futures", "rest",
                   "https://api.gateio.ws/api/v4/futures/usdt/tickers", 30),
    DataSourceSpec("mexc_spot", "prices", "MEXC Spot", "rest",
                   "https://api.mexc.com/api/v3/ticker/24hr", 30),
    DataSourceSpec("bitget_spot", "prices", "Bitget Spot", "rest",
                   "https://api.bitget.com/api/v2/spot/market/tickers", 30),
    DataSourceSpec("bitget_futures", "prices", "Bitget Futures", "rest",
                   "https://api.bitget.com/api/v2/mix/market/tickers", 30),
    DataSourceSpec("htx_spot", "prices", "HTX Spot", "rest",
                   "https://api.huobi.pro/market/tickers", 30),
    DataSourceSpec("bitstamp_spot", "prices", "Bitstamp Spot", "rest",
                   "https://www.bitstamp.net/api/v2/ticker/btcusd/", 30),
    DataSourceSpec("deribit_index", "prices", "Deribit Index", "rest",
                   "https://www.deribit.com/api/v2/public/get_index_price", 15),
    DataSourceSpec("phemex_spot", "prices", "Phemex Spot", "rest",
                   "https://api.phemex.com/md/v2/ticker/24hr/all", 30),
    DataSourceSpec("bingx_spot", "prices", "BingX Spot", "rest",
                   "https://open-api.bingx.com/openApi/spot/v1/ticker/24hr", 30),
    DataSourceSpec("whitebit_spot", "prices", "WhiteBIT Spot", "rest",
                   "https://whitebit.com/api/v4/public/ticker", 30),
    DataSourceSpec("jupiter_quote", "defi", "Jupiter Quote", "rest",
                   "https://quote-api.jup.ag/v6/quote", 60),
    DataSourceSpec("raydium_pools", "defi", "Raydium Pools", "rest",
                   "https://api.raydium.io/v2/main/pairs", 120),
    DataSourceSpec("orca_whirlpools", "defi", "Orca Whirlpools", "rest",
                   "https://api.mainnet.orca.so/v1/whirlpool/list", 120),
    DataSourceSpec("curve_pools", "defi", "Curve Pools", "rest",
                   "https://api.curve.fi/api/getPools/ethereum/main", 300),
    DataSourceSpec("aave_rates", "defi", "Aave Rates", "rest",
                   "https://aave-api-v2.aave.com/data/liquidity/v2", 300),
    DataSourceSpec("lido_steth", "defi", "Lido stETH APR", "rest",
                   "https://eth-api.lido.fi/v1/protocol/steth/apr/last", 3600),
    DataSourceSpec("balancer_pools", "defi", "Balancer Pools", "rest",
                   "https://api-v3.balancer.fi/pools", 300),
    DataSourceSpec("sushiswap_subgraph", "defi", "SushiSwap Subgraph", "subgraph",
                   "https://api.thegraph.com/subgraphs/name/sushiswap/exchange", 300),
    DataSourceSpec("mempool_space", "onchain", "Mempool.space Fees", "rest",
                   "https://mempool.space/api/v1/fees/recommended", 60),
    DataSourceSpec("blockchair_btc_stats", "onchain", "Blockchair BTC Stats", "rest",
                   "https://api.blockchair.com/bitcoin/stats", 300, env_key="BLOCKCHAIR_API_KEY"),
    DataSourceSpec("etherscan_gas", "onchain", "Etherscan Gas Tracker", "rest",
                   "https://api.etherscan.io/api?module=gastracker", 60, env_key="ETHERSCAN_API_KEY"),
    DataSourceSpec("reddit_bitcoin", "sentiment", "Reddit r/bitcoin", "rest",
                   "https://www.reddit.com/r/bitcoin/hot.json", 120),
    DataSourceSpec("reddit_ethfinance", "sentiment", "Reddit r/ethfinance", "rest",
                   "https://www.reddit.com/r/ethfinance/hot.json", 120),
    DataSourceSpec("alternative_me_fng", "sentiment", "Fear & Greed Index", "rest",
                   "https://api.alternative.me/fng/", 3600),
    DataSourceSpec("theblock_rss", "news", "The Block RSS", "rss",
                   "https://www.theblock.co/rss.xml", 300),
    DataSourceSpec("dlnews_rss", "news", "DL News RSS", "rss",
                   "https://www.dlnews.com/rss", 300),
    DataSourceSpec("treasury_yield_10y", "macro", "US 10Y Treasury", "rest",
                   "https://api.stlouisfed.org/fred/series/observations?series_id=DGS10", 3600, env_key="FRED_API_KEY"),
    DataSourceSpec("vix_yahoo", "macro", "VIX Index", "rest",
                   "https://query1.finance.yahoo.com/v8/finance/chart/%5EVIX", 300),
    DataSourceSpec("gold_spot_yahoo", "macro", "Gold Spot", "rest",
                   "https://query1.finance.yahoo.com/v8/finance/chart/GC=F", 300),
    DataSourceSpec("oil_wti_yahoo", "macro", "WTI Oil", "rest",
                   "https://query1.finance.yahoo.com/v8/finance/chart/CL=F", 300),
    DataSourceSpec("eurusd_yahoo", "macro", "EUR/USD", "rest",
                   "https://query1.finance.yahoo.com/v8/finance/chart/EURUSD=X", 300),
)
