"""Six Heroes binding resolver for CAPABILITY_BUILD_826 program.

Maps capability IDs to primary Hero, entry path, and binding status using the
canonical HERO_ENGINES registry (docs/HERO_SIX_BINDING_REPORT.json lineage).
"""
from __future__ import annotations

from typing import Any

# Canonical six-hero engines — capability_id membership from pentagonal binding report.
HERO_ENGINES: dict[str, dict[str, Any]] = {
    "Single-Sentence Oracle": {
        "live_endpoint": {"method": "GET", "path": "/api/oracle/persona-clarity/demo"},
        "ui_path": "/dashboard",
        "capability_ids": {
            24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 40, 47, 48, 50, 55, 56, 59, 66, 69, 86, 89, 90,
        },
    },
    "Public Accuracy Ledger": {
        "live_endpoint": {"method": "GET", "path": "/api/oracle/audit-chain/verify"},
        "ui_path": "/oracle-accuracy",
        "capability_ids": {61, 63, 64, 65, 100},
    },
    "Arbitrage Scanner": {
        "live_endpoint": {"method": "GET", "path": "/api/arbitrage/scanner/status"},
        "ui_path": "/dashboard",
        "capability_ids": {11, 40, 47, 48, 50, 52, 57, 69, 82, 83, 85, 86, 87, 88, 89},
    },
    "Whale Signal vs Noise": {
        "live_endpoint": {"method": "GET", "path": "/api/whale/signal-vs-noise"},
        "ui_path": "/dashboard",
        "capability_ids": {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 15, 16, 18, 19, 20, 21, 22, 23, 72, 75, 81, 85, 86, 88, 91, 92, 98},
    },
    "Stealth Advisor": {
        "live_endpoint": {"method": "POST", "path": "/api/whale/stealth-advisor"},
        "ui_path": "/dashboard",
        "capability_ids": {40, 50, 85, 86, 87, 88},
    },
    "B2B Feed": {
        "live_endpoint": {"method": "GET", "path": "/api/b2b/demo"},
        "ui_path": "/institutional",
        "capability_ids": {67, 68, 71, 74, 77, 81, 84, 91, 92, 98, 99, 100},
    },
}

# Batch01 build IDs with explicit hero when not in HERO_ENGINES lists above.
_BATCH01_FALLBACK: dict[int, str] = {
    17: "Whale Signal vs Noise",
}

# Batch02 (26–50) — oracle / on-chain / market surfaces
_BATCH02_FALLBACK: dict[int, str] = {
    **{cid: "Single-Sentence Oracle" for cid in range(26, 36)},
    36: "Whale Signal vs Noise",
    37: "Whale Signal vs Noise",
    38: "Whale Signal vs Noise",
    39: "Whale Signal vs Noise",
    41: "Whale Signal vs Noise",
    42: "Whale Signal vs Noise",
    43: "Whale Signal vs Noise",
    44: "Whale Signal vs Noise",
    45: "Whale Signal vs Noise",
    46: "Whale Signal vs Noise",
    47: "Single-Sentence Oracle",
    48: "Single-Sentence Oracle",
    49: "Arbitrage Scanner",
    50: "Single-Sentence Oracle",
}

# Build batch 03 (51–75) — official batch02 spine
_BATCH03_FALLBACK: dict[int, str] = {
    51: "Single-Sentence Oracle",
    52: "Arbitrage Scanner",
    53: "Single-Sentence Oracle",
    54: "Arbitrage Scanner",
    58: "Single-Sentence Oracle",
    60: "Whale Signal vs Noise",
    62: "B2B Feed",
    63: "Public Accuracy Ledger",
    64: "Public Accuracy Ledger",
    65: "Public Accuracy Ledger",
    66: "Single-Sentence Oracle",
    67: "B2B Feed",
    68: "B2B Feed",
    70: "Whale Signal vs Noise",
    71: "Whale Signal vs Noise",
    72: "Whale Signal vs Noise",
    73: "Whale Signal vs Noise",
    74: "B2B Feed",
    75: "Whale Signal vs Noise",
    76: "Whale Signal vs Noise",
    77: "B2B Feed",
    78: "Whale Signal vs Noise",
    79: "Arbitrage Scanner",
    80: "Whale Signal vs Noise",
    81: "Whale Signal vs Noise",
    82: "Arbitrage Scanner",
    83: "Arbitrage Scanner",
    84: "B2B Feed",
    85: "Whale Signal vs Noise",
    86: "Single-Sentence Oracle",
    87: "Stealth Advisor",
    88: "Stealth Advisor",
    89: "Single-Sentence Oracle",
    90: "Single-Sentence Oracle",
    91: "B2B Feed",
    92: "B2B Feed",
    93: "Single-Sentence Oracle",
    94: "Single-Sentence Oracle",
    95: "Single-Sentence Oracle",
    96: "Single-Sentence Oracle",
    97: "Single-Sentence Oracle",
    98: "B2B Feed",
    99: "B2B Feed",
    100: "Public Accuracy Ledger",
}

# Build batches 05–06 (101–150) — official batch03 spine
_BATCH05_FALLBACK: dict[int, str] = {
    101: "Single-Sentence Oracle",
    102: "Single-Sentence Oracle",
    103: "B2B Feed",
    104: "B2B Feed",
    105: "Whale Signal vs Noise",
    106: "Public Accuracy Ledger",
    107: "Public Accuracy Ledger",
    108: "B2B Feed",
    109: "Single-Sentence Oracle",
    110: "Single-Sentence Oracle",
    111: "Whale Signal vs Noise",
    112: "Whale Signal vs Noise",
    113: "Whale Signal vs Noise",
    114: "Whale Signal vs Noise",
    115: "Whale Signal vs Noise",
    116: "Whale Signal vs Noise",
    117: "Public Accuracy Ledger",
    118: "Whale Signal vs Noise",
    119: "Whale Signal vs Noise",
    120: "Whale Signal vs Noise",
    121: "Whale Signal vs Noise",
    122: "Whale Signal vs Noise",
    123: "Whale Signal vs Noise",
    124: "Arbitrage Scanner",
    125: "Arbitrage Scanner",
    126: "Arbitrage Scanner",
    127: "Whale Signal vs Noise",
    128: "Whale Signal vs Noise",
    129: "Single-Sentence Oracle",
    130: "Single-Sentence Oracle",
    131: "Single-Sentence Oracle",
    132: "Single-Sentence Oracle",
    133: "Single-Sentence Oracle",
    134: "Single-Sentence Oracle",
    135: "Single-Sentence Oracle",
    136: "Single-Sentence Oracle",
    137: "Whale Signal vs Noise",
    138: "Whale Signal vs Noise",
    139: "Whale Signal vs Noise",
    140: "Whale Signal vs Noise",
    141: "Whale Signal vs Noise",
    142: "Whale Signal vs Noise",
    143: "Whale Signal vs Noise",
    144: "Whale Signal vs Noise",
    145: "Whale Signal vs Noise",
    146: "B2B Feed",
    147: "Arbitrage Scanner",
    148: "Single-Sentence Oracle",
    149: "Whale Signal vs Noise",
    150: "Whale Signal vs Noise",
}

_BATCH07_FALLBACK: dict[int, str] = {
    151: "Single-Sentence Oracle",
    152: "Single-Sentence Oracle",
    153: "Public Accuracy Ledger",
    154: "Single-Sentence Oracle",
    155: "Single-Sentence Oracle",
    156: "Single-Sentence Oracle",
    157: "Single-Sentence Oracle",
    158: "Single-Sentence Oracle",
    159: "B2B Feed",
    160: "B2B Feed",
    161: "B2B Feed",
    162: "Public Accuracy Ledger",
    163: "Single-Sentence Oracle",
    164: "Single-Sentence Oracle",
    165: "Single-Sentence Oracle",
    166: "Single-Sentence Oracle",
    167: "Single-Sentence Oracle",
    168: "Single-Sentence Oracle",
    169: "Single-Sentence Oracle",
    170: "Single-Sentence Oracle",
    171: "Single-Sentence Oracle",
    172: "Single-Sentence Oracle",
    173: "Single-Sentence Oracle",
    174: "Single-Sentence Oracle",
    175: "Single-Sentence Oracle",
    176: "Single-Sentence Oracle",
    177: "Single-Sentence Oracle",
    178: "Single-Sentence Oracle",
    179: "Single-Sentence Oracle",
    180: "Single-Sentence Oracle",
    181: "Single-Sentence Oracle",
    182: "Single-Sentence Oracle",
    183: "Whale Signal vs Noise",
    184: "Whale Signal vs Noise",
    185: "Whale Signal vs Noise",
    186: "Whale Signal vs Noise",
    187: "Whale Signal vs Noise",
    188: "Whale Signal vs Noise",
    189: "Whale Signal vs Noise",
    190: "Whale Signal vs Noise",
    191: "Whale Signal vs Noise",
    192: "Whale Signal vs Noise",
    193: "Whale Signal vs Noise",
    194: "Whale Signal vs Noise",
    195: "Whale Signal vs Noise",
    196: "Single-Sentence Oracle",
    197: "Whale Signal vs Noise",
    198: "Single-Sentence Oracle",
    199: "Single-Sentence Oracle",
    200: "Single-Sentence Oracle",
    201: "Whale Signal vs Noise",
    202: "Whale Signal vs Noise",
    203: "Single-Sentence Oracle",
    204: "Single-Sentence Oracle",
    205: "Single-Sentence Oracle",
    206: "Arbitrage Scanner",
    207: "Single-Sentence Oracle",
    208: "Single-Sentence Oracle",
    209: "Single-Sentence Oracle",
    210: "Single-Sentence Oracle",
    211: "Single-Sentence Oracle",
    212: "Single-Sentence Oracle",
    213: "Single-Sentence Oracle",
    214: "Single-Sentence Oracle",
    215: "Single-Sentence Oracle",
    216: "Single-Sentence Oracle",
    217: "B2B Feed",
    218: "Single-Sentence Oracle",
    219: "Public Accuracy Ledger",
    220: "Single-Sentence Oracle",
    221: "Public Accuracy Ledger",
    222: "Public Accuracy Ledger",
    223: "Single-Sentence Oracle",
    224: "Single-Sentence Oracle",
    225: "Single-Sentence Oracle",
    226: "Single-Sentence Oracle",
    227: "Single-Sentence Oracle",
    228: "Arbitrage Scanner",
    229: "Arbitrage Scanner",
    230: "Arbitrage Scanner",
    231: "Arbitrage Scanner",
    232: "Single-Sentence Oracle",
    233: "Arbitrage Scanner",
    234: "Single-Sentence Oracle",
    235: "Single-Sentence Oracle",
    236: "Single-Sentence Oracle",
    237: "Single-Sentence Oracle",
    238: "Single-Sentence Oracle",
    239: "Single-Sentence Oracle",
    240: "Single-Sentence Oracle",
    241: "Single-Sentence Oracle",
    242: "Single-Sentence Oracle",
    243: "Single-Sentence Oracle",
    244: "Single-Sentence Oracle",
    245: "Single-Sentence Oracle",
    246: "Public Accuracy Ledger",
    247: "B2B Feed",
    248: "Single-Sentence Oracle",
    249: "B2B Feed",
    250: "B2B Feed",
}


_BATCH11_FALLBACK: dict[int, str] = {
    251: "Single-Sentence Oracle",
    252: "Arbitrage Scanner",
    253: "Arbitrage Scanner",
    254: "Arbitrage Scanner",
    255: "B2B Feed",
    256: "Arbitrage Scanner",
    257: "Whale Signal vs Noise",
    258: "Whale Signal vs Noise",
    259: "Arbitrage Scanner",
    260: "Arbitrage Scanner",
    261: "Arbitrage Scanner",
    262: "B2B Feed",
    263: "Arbitrage Scanner",
    264: "Arbitrage Scanner",
    265: "Arbitrage Scanner",
    266: "Whale Signal vs Noise",
    267: "Whale Signal vs Noise",
    268: "Arbitrage Scanner",
    269: "Whale Signal vs Noise",
    270: "Arbitrage Scanner",
    271: "Arbitrage Scanner",
    272: "B2B Feed",
    273: "Arbitrage Scanner",
    274: "Arbitrage Scanner",
    275: "Single-Sentence Oracle",
    276: "Whale Signal vs Noise",
    277: "Whale Signal vs Noise",
    278: "Whale Signal vs Noise",
    279: "Whale Signal vs Noise",
    280: "Whale Signal vs Noise",
    281: "Whale Signal vs Noise",
    282: "Whale Signal vs Noise",
    283: "Whale Signal vs Noise",
    284: "Whale Signal vs Noise",
    285: "Whale Signal vs Noise",
    286: "Whale Signal vs Noise",
    287: "Whale Signal vs Noise",
    288: "Whale Signal vs Noise",
    289: "Whale Signal vs Noise",
    290: "Whale Signal vs Noise",
    291: "Whale Signal vs Noise",
    292: "Single-Sentence Oracle",
    293: "Whale Signal vs Noise",
    294: "Whale Signal vs Noise",
    295: "Single-Sentence Oracle",
    296: "Whale Signal vs Noise",
    297: "Whale Signal vs Noise",
    298: "B2B Feed",
    299: "Single-Sentence Oracle",
    300: "Single-Sentence Oracle",
}

_BATCH13_FALLBACK: dict[int, str] = {
    301: "Single-Sentence Oracle",
    302: "Single-Sentence Oracle",
    303: "Single-Sentence Oracle",
    304: "Single-Sentence Oracle",
    305: "Single-Sentence Oracle",
    306: "Single-Sentence Oracle",
    307: "Single-Sentence Oracle",
    308: "Single-Sentence Oracle",
    309: "Single-Sentence Oracle",
    310: "Single-Sentence Oracle",
    311: "Single-Sentence Oracle",
    312: "Single-Sentence Oracle",
    313: "Whale Signal vs Noise",
    314: "Single-Sentence Oracle",
    315: "Single-Sentence Oracle",
    316: "Single-Sentence Oracle",
    317: "Single-Sentence Oracle",
    318: "Single-Sentence Oracle",
    319: "Single-Sentence Oracle",
    320: "Whale Signal vs Noise",
    321: "Single-Sentence Oracle",
    322: "Single-Sentence Oracle",
    323: "B2B Feed",
    324: "Public Accuracy Ledger",
    325: "Arbitrage Scanner",
    326: "Whale Signal vs Noise",
    327: "Whale Signal vs Noise",
    328: "Whale Signal vs Noise",
    329: "Whale Signal vs Noise",
    330: "Whale Signal vs Noise",
    331: "Whale Signal vs Noise",
    332: "Whale Signal vs Noise",
    333: "Whale Signal vs Noise",
    334: "Whale Signal vs Noise",
    335: "Arbitrage Scanner",
    336: "Whale Signal vs Noise",
    337: "Whale Signal vs Noise",
    338: "Public Accuracy Ledger",
    339: "Public Accuracy Ledger",
    340: "B2B Feed",
    341: "Whale Signal vs Noise",
    342: "Public Accuracy Ledger",
    343: "Public Accuracy Ledger",
    344: "B2B Feed",
    345: "Single-Sentence Oracle",
    346: "Whale Signal vs Noise",
    347: "Whale Signal vs Noise",
    348: "Whale Signal vs Noise",
    349: "Whale Signal vs Noise",
    350: "Whale Signal vs Noise",
}

_BATCH15_FALLBACK: dict[int, str] = {
    351: "Whale Signal vs Noise",
    352: "Whale Signal vs Noise",
    353: "Whale Signal vs Noise",
    354: "Whale Signal vs Noise",
    355: "Whale Signal vs Noise",
    356: "Whale Signal vs Noise",
    357: "Whale Signal vs Noise",
    358: "Whale Signal vs Noise",
    359: "Whale Signal vs Noise",
    360: "Whale Signal vs Noise",
    361: "Whale Signal vs Noise",
    362: "Whale Signal vs Noise",
    363: "Whale Signal vs Noise",
    364: "Single-Sentence Oracle",
    365: "Whale Signal vs Noise",
    366: "Public Accuracy Ledger",
    367: "Public Accuracy Ledger",
    368: "B2B Feed",
    369: "Single-Sentence Oracle",
    370: "Whale Signal vs Noise",
    371: "Whale Signal vs Noise",
    372: "Whale Signal vs Noise",
    373: "Whale Signal vs Noise",
    374: "Whale Signal vs Noise",
    375: "Whale Signal vs Noise",
    376: "Whale Signal vs Noise",
    377: "Single-Sentence Oracle",
    378: "Whale Signal vs Noise",
    379: "B2B Feed",
    380: "Whale Signal vs Noise",
    381: "Whale Signal vs Noise",
    382: "Whale Signal vs Noise",
    383: "Whale Signal vs Noise",
    384: "Single-Sentence Oracle",
    385: "Whale Signal vs Noise",
    386: "Whale Signal vs Noise",
    387: "Whale Signal vs Noise",
    388: "Single-Sentence Oracle",
    389: "Whale Signal vs Noise",
    390: "Whale Signal vs Noise",
    391: "Whale Signal vs Noise",
    392: "Single-Sentence Oracle",
    393: "Whale Signal vs Noise",
    394: "Whale Signal vs Noise",
    395: "Whale Signal vs Noise",
    396: "Whale Signal vs Noise",
    397: "Whale Signal vs Noise",
    398: "Whale Signal vs Noise",
    399: "Arbitrage Scanner",
    400: "Whale Signal vs Noise",
}

_BATCH17_FALLBACK: dict[int, str] = {
    401: "Single-Sentence Oracle",
    402: "Single-Sentence Oracle",
    403: "Single-Sentence Oracle",
    404: "Single-Sentence Oracle",
    405: "Single-Sentence Oracle",
    406: "Single-Sentence Oracle",
    407: "Arbitrage Scanner",
    408: "Single-Sentence Oracle",
    409: "Single-Sentence Oracle",
    410: "Single-Sentence Oracle",
    411: "Single-Sentence Oracle",
    412: "B2B Feed",
    413: "Single-Sentence Oracle",
    414: "Single-Sentence Oracle",
    415: "B2B Feed",
    416: "Single-Sentence Oracle",
    417: "Single-Sentence Oracle",
    418: "Single-Sentence Oracle",
    419: "Single-Sentence Oracle",
    420: "Single-Sentence Oracle",
    421: "Single-Sentence Oracle",
    422: "Single-Sentence Oracle",
    423: "Single-Sentence Oracle",
    424: "Single-Sentence Oracle",
    425: "Single-Sentence Oracle",
    426: "Single-Sentence Oracle",
    427: "Single-Sentence Oracle",
    428: "B2B Feed",
    429: "B2B Feed",
    430: "Single-Sentence Oracle",
    431: "Single-Sentence Oracle",
    432: "Single-Sentence Oracle",
    433: "Whale Signal vs Noise",
    434: "Single-Sentence Oracle",
    435: "Single-Sentence Oracle",
    436: "Single-Sentence Oracle",
    437: "Single-Sentence Oracle",
    438: "Single-Sentence Oracle",
    439: "Single-Sentence Oracle",
    440: "Arbitrage Scanner",
    441: "Single-Sentence Oracle",
    442: "Single-Sentence Oracle",
    443: "Single-Sentence Oracle",
    444: "Single-Sentence Oracle",
    445: "Single-Sentence Oracle",
    446: "Single-Sentence Oracle",
    447: "Single-Sentence Oracle",
    448: "B2B Feed",
    449: "Whale Signal vs Noise",
    450: "Single-Sentence Oracle",
}

_BATCH19_FALLBACK: dict[int, str] = {
    451: "Single-Sentence Oracle",
    452: "Single-Sentence Oracle",
    453: "Single-Sentence Oracle",
    454: "B2B Feed",
    455: "Single-Sentence Oracle",
    456: "Single-Sentence Oracle",
    457: "Single-Sentence Oracle",
    458: "Single-Sentence Oracle",
    459: "Whale Signal vs Noise",
    460: "Single-Sentence Oracle",
    461: "Whale Signal vs Noise",
    462: "Whale Signal vs Noise",
    463: "Single-Sentence Oracle",
    464: "Single-Sentence Oracle",
    465: "Whale Signal vs Noise",
    466: "Single-Sentence Oracle",
    467: "Single-Sentence Oracle",
    468: "Public Accuracy Ledger",
    469: "Single-Sentence Oracle",
    470: "Single-Sentence Oracle",
    471: "Single-Sentence Oracle",
    472: "Single-Sentence Oracle",
    473: "Single-Sentence Oracle",
    474: "Single-Sentence Oracle",
    475: "Single-Sentence Oracle",
    476: "B2B Feed",
    477: "Whale Signal vs Noise",
    478: "Public Accuracy Ledger",
    479: "Single-Sentence Oracle",
    480: "B2B Feed",
    481: "Single-Sentence Oracle",
    482: "B2B Feed",
    483: "Single-Sentence Oracle",
    484: "Single-Sentence Oracle",
    485: "Arbitrage Scanner",
    486: "B2B Feed",
    487: "Arbitrage Scanner",
    488: "Single-Sentence Oracle",
    489: "Public Accuracy Ledger",
    490: "Whale Signal vs Noise",
    491: "Single-Sentence Oracle",
    492: "Single-Sentence Oracle",
    493: "Single-Sentence Oracle",
    494: "Single-Sentence Oracle",
    495: "Single-Sentence Oracle",
    496: "Single-Sentence Oracle",
    497: "Single-Sentence Oracle",
    498: "Single-Sentence Oracle",
    499: "B2B Feed",
    500: "Public Accuracy Ledger",
}

_BATCH21_FALLBACK: dict[int, str] = {
    501: "B2B Feed",
    502: "B2B Feed",
    503: "Single-Sentence Oracle",
    504: "B2B Feed",
    505: "Whale Signal vs Noise",
    506: "Whale Signal vs Noise",
    507: "Whale Signal vs Noise",
    508: "Arbitrage Scanner",
    509: "Arbitrage Scanner",
    510: "Arbitrage Scanner",
    511: "Arbitrage Scanner",
    512: "Arbitrage Scanner",
    513: "B2B Feed",
    514: "B2B Feed",
    515: "B2B Feed",
    516: "B2B Feed",
    517: "B2B Feed",
    518: "B2B Feed",
    519: "Whale Signal vs Noise",
    520: "Single-Sentence Oracle",
    521: "Arbitrage Scanner",
    522: "B2B Feed",
    523: "Public Accuracy Ledger",
    524: "Public Accuracy Ledger",
    525: "Public Accuracy Ledger",
    526: "Single-Sentence Oracle",
    527: "Arbitrage Scanner",
    528: "Arbitrage Scanner",
    529: "Arbitrage Scanner",
    530: "Arbitrage Scanner",
    531: "B2B Feed",
    532: "Arbitrage Scanner",
    533: "Whale Signal vs Noise",
    534: "Arbitrage Scanner",
    535: "Whale Signal vs Noise",
    536: "Arbitrage Scanner",
    537: "Arbitrage Scanner",
    538: "Arbitrage Scanner",
    539: "Whale Signal vs Noise",
    540: "Whale Signal vs Noise",
    541: "Single-Sentence Oracle",
    542: "Arbitrage Scanner",
    543: "Arbitrage Scanner",
    544: "B2B Feed",
    545: "Whale Signal vs Noise",
    546: "Single-Sentence Oracle",
    547: "Single-Sentence Oracle",
    548: "Single-Sentence Oracle",
    549: "Arbitrage Scanner",
    550: "B2B Feed",
}

_BATCH23_FALLBACK: dict[int, str] = {
    551: "Single-Sentence Oracle",
    552: "Single-Sentence Oracle",
    553: "Single-Sentence Oracle",
    554: "Single-Sentence Oracle",
    555: "Single-Sentence Oracle",
    556: "Single-Sentence Oracle",
    557: "Single-Sentence Oracle",
    558: "Single-Sentence Oracle",
    559: "Single-Sentence Oracle",
    560: "Single-Sentence Oracle",
    561: "Single-Sentence Oracle",
    562: "Single-Sentence Oracle",
    563: "Single-Sentence Oracle",
    564: "Single-Sentence Oracle",
    565: "Single-Sentence Oracle",
    566: "Single-Sentence Oracle",
    567: "Single-Sentence Oracle",
    568: "Single-Sentence Oracle",
    569: "Single-Sentence Oracle",
    570: "Single-Sentence Oracle",
    571: "Single-Sentence Oracle",
    572: "Single-Sentence Oracle",
    573: "Single-Sentence Oracle",
    574: "Single-Sentence Oracle",
    575: "Single-Sentence Oracle",
    576: "Single-Sentence Oracle",
    577: "Single-Sentence Oracle",
    578: "Single-Sentence Oracle",
    579: "Single-Sentence Oracle",
    580: "Single-Sentence Oracle",
    581: "Single-Sentence Oracle",
    582: "Single-Sentence Oracle",
    583: "Single-Sentence Oracle",
    584: "Single-Sentence Oracle",
    585: "Single-Sentence Oracle",
    586: "Single-Sentence Oracle",
    587: "Single-Sentence Oracle",
    588: "Single-Sentence Oracle",
    589: "Single-Sentence Oracle",
    590: "Single-Sentence Oracle",
    591: "Single-Sentence Oracle",
    592: "Single-Sentence Oracle",
    593: "Single-Sentence Oracle",
    594: "Single-Sentence Oracle",
    595: "Single-Sentence Oracle",
    596: "Single-Sentence Oracle",
    597: "Single-Sentence Oracle",
    598: "Single-Sentence Oracle",
    599: "Single-Sentence Oracle",
    600: "Single-Sentence Oracle",
}

_BATCH25_FALLBACK: dict[int, str] = {
    601: "Single-Sentence Oracle",
    602: "Single-Sentence Oracle",
    603: "Single-Sentence Oracle",
    604: "Single-Sentence Oracle",
    605: "Single-Sentence Oracle",
    606: "Single-Sentence Oracle",
    607: "Single-Sentence Oracle",
    608: "Single-Sentence Oracle",
    609: "Single-Sentence Oracle",
    610: "Single-Sentence Oracle",
    611: "Single-Sentence Oracle",
    612: "Single-Sentence Oracle",
    613: "Single-Sentence Oracle",
    614: "Single-Sentence Oracle",
    615: "Single-Sentence Oracle",
    616: "Single-Sentence Oracle",
    617: "Single-Sentence Oracle",
    618: "Single-Sentence Oracle",
    619: "Single-Sentence Oracle",
    620: "Single-Sentence Oracle",
    621: "Single-Sentence Oracle",
    622: "Single-Sentence Oracle",
    623: "Single-Sentence Oracle",
    624: "Single-Sentence Oracle",
    625: "Single-Sentence Oracle",
    626: "Single-Sentence Oracle",
    627: "Single-Sentence Oracle",
    628: "Single-Sentence Oracle",
    629: "Single-Sentence Oracle",
    630: "Single-Sentence Oracle",
    631: "Single-Sentence Oracle",
    632: "Single-Sentence Oracle",
    633: "Single-Sentence Oracle",
    634: "Single-Sentence Oracle",
    635: "Single-Sentence Oracle",
    636: "Single-Sentence Oracle",
    637: "Single-Sentence Oracle",
    638: "Single-Sentence Oracle",
    639: "Single-Sentence Oracle",
    640: "Single-Sentence Oracle",
    641: "Single-Sentence Oracle",
    642: "Single-Sentence Oracle",
    643: "Single-Sentence Oracle",
    644: "Single-Sentence Oracle",
    645: "Single-Sentence Oracle",
    646: "Single-Sentence Oracle",
    647: "Single-Sentence Oracle",
    648: "B2B Feed",
    649: "Single-Sentence Oracle",
    650: "Single-Sentence Oracle",
}

_BATCH27_FALLBACK: dict[int, str] = {
    651: "Single-Sentence Oracle",
    652: "Single-Sentence Oracle",
    653: "Single-Sentence Oracle",
    654: "Single-Sentence Oracle",
    655: "Single-Sentence Oracle",
    656: "Single-Sentence Oracle",
    657: "Single-Sentence Oracle",
    658: "Single-Sentence Oracle",
    659: "Single-Sentence Oracle",
    660: "Single-Sentence Oracle",
    661: "Single-Sentence Oracle",
    662: "Single-Sentence Oracle",
    663: "Single-Sentence Oracle",
    664: "Single-Sentence Oracle",
    665: "Single-Sentence Oracle",
    666: "Single-Sentence Oracle",
    667: "Single-Sentence Oracle",
    668: "Single-Sentence Oracle",
    669: "Single-Sentence Oracle",
    670: "Single-Sentence Oracle",
    671: "Single-Sentence Oracle",
    672: "Single-Sentence Oracle",
    673: "Single-Sentence Oracle",
    674: "Single-Sentence Oracle",
    675: "Single-Sentence Oracle",
    676: "Single-Sentence Oracle",
    677: "Single-Sentence Oracle",
    678: "Single-Sentence Oracle",
    679: "Single-Sentence Oracle",
    680: "Single-Sentence Oracle",
    681: "Single-Sentence Oracle",
    682: "Single-Sentence Oracle",
    683: "Single-Sentence Oracle",
    684: "Single-Sentence Oracle",
    685: "Single-Sentence Oracle",
    686: "Single-Sentence Oracle",
    687: "Single-Sentence Oracle",
    688: "Single-Sentence Oracle",
    689: "Single-Sentence Oracle",
    690: "B2B Feed",
    691: "B2B Feed",
    692: "Single-Sentence Oracle",
    693: "Single-Sentence Oracle",
    694: "Single-Sentence Oracle",
    695: "Single-Sentence Oracle",
    696: "Single-Sentence Oracle",
    697: "Single-Sentence Oracle",
    698: "Single-Sentence Oracle",
    699: "Single-Sentence Oracle",
    700: "Single-Sentence Oracle",
}

_BATCH29_FALLBACK: dict[int, str] = {
    701: "Single-Sentence Oracle",
    702: "Single-Sentence Oracle",
    703: "Single-Sentence Oracle",
    704: "Single-Sentence Oracle",
    705: "Single-Sentence Oracle",
    706: "Single-Sentence Oracle",
    707: "Single-Sentence Oracle",
    708: "Single-Sentence Oracle",
    709: "Single-Sentence Oracle",
    710: "Single-Sentence Oracle",
    711: "Single-Sentence Oracle",
    712: "Single-Sentence Oracle",
    713: "Single-Sentence Oracle",
    714: "Single-Sentence Oracle",
    715: "Single-Sentence Oracle",
    716: "Single-Sentence Oracle",
    717: "Single-Sentence Oracle",
    718: "Single-Sentence Oracle",
    719: "Single-Sentence Oracle",
    720: "Single-Sentence Oracle",
    721: "Single-Sentence Oracle",
    722: "Single-Sentence Oracle",
    723: "Single-Sentence Oracle",
    724: "Single-Sentence Oracle",
    725: "Single-Sentence Oracle",
    726: "Single-Sentence Oracle",
    727: "Single-Sentence Oracle",
    728: "Single-Sentence Oracle",
    729: "Single-Sentence Oracle",
    730: "Single-Sentence Oracle",
    731: "Single-Sentence Oracle",
    732: "Single-Sentence Oracle",
    733: "Single-Sentence Oracle",
    734: "Single-Sentence Oracle",
    735: "Single-Sentence Oracle",
    736: "Single-Sentence Oracle",
    737: "Single-Sentence Oracle",
    738: "Single-Sentence Oracle",
    739: "Single-Sentence Oracle",
    740: "Single-Sentence Oracle",
    741: "Single-Sentence Oracle",
    742: "Single-Sentence Oracle",
    743: "Single-Sentence Oracle",
    744: "Single-Sentence Oracle",
    745: "Single-Sentence Oracle",
    746: "Single-Sentence Oracle",
    747: "Single-Sentence Oracle",
    748: "Single-Sentence Oracle",
    749: "Single-Sentence Oracle",
    750: "Single-Sentence Oracle",
}

_BATCH31_FALLBACK: dict[int, str] = {
    751: "Single-Sentence Oracle",
    752: "Single-Sentence Oracle",
    753: "Single-Sentence Oracle",
    754: "Single-Sentence Oracle",
    755: "Single-Sentence Oracle",
    756: "Single-Sentence Oracle",
    757: "Single-Sentence Oracle",
    758: "Single-Sentence Oracle",
    759: "Single-Sentence Oracle",
    760: "Single-Sentence Oracle",
    761: "Single-Sentence Oracle",
    762: "Single-Sentence Oracle",
    763: "Single-Sentence Oracle",
    764: "Single-Sentence Oracle",
    765: "Single-Sentence Oracle",
    766: "Single-Sentence Oracle",
    767: "Single-Sentence Oracle",
    768: "Single-Sentence Oracle",
    769: "Single-Sentence Oracle",
    770: "Single-Sentence Oracle",
    771: "Single-Sentence Oracle",
    772: "Single-Sentence Oracle",
    773: "Single-Sentence Oracle",
    774: "Single-Sentence Oracle",
    775: "Single-Sentence Oracle",
    776: "Single-Sentence Oracle",
    777: "Single-Sentence Oracle",
    778: "Single-Sentence Oracle",
    779: "Single-Sentence Oracle",
    780: "Single-Sentence Oracle",
    781: "Single-Sentence Oracle",
    782: "Single-Sentence Oracle",
    783: "Single-Sentence Oracle",
    784: "Single-Sentence Oracle",
    785: "Single-Sentence Oracle",
    786: "Single-Sentence Oracle",
    787: "Single-Sentence Oracle",
    788: "Single-Sentence Oracle",
    789: "Single-Sentence Oracle",
    790: "Single-Sentence Oracle",
    791: "Single-Sentence Oracle",
    792: "Single-Sentence Oracle",
    793: "Single-Sentence Oracle",
    794: "Single-Sentence Oracle",
    795: "Single-Sentence Oracle",
    796: "Single-Sentence Oracle",
    797: "Single-Sentence Oracle",
    798: "Single-Sentence Oracle",
    799: "Single-Sentence Oracle",
    800: "Single-Sentence Oracle",
}

_BATCH33_FALLBACK: dict[int, str] = {
    801: "Single-Sentence Oracle",
    802: "Single-Sentence Oracle",
    803: "Single-Sentence Oracle",
    804: "Single-Sentence Oracle",
    805: "Single-Sentence Oracle",
    806: "Single-Sentence Oracle",
    807: "Single-Sentence Oracle",
    808: "Single-Sentence Oracle",
    809: "Single-Sentence Oracle",
    810: "Single-Sentence Oracle",
    811: "Single-Sentence Oracle",
    812: "Single-Sentence Oracle",
    813: "Single-Sentence Oracle",
    814: "Single-Sentence Oracle",
    815: "Single-Sentence Oracle",
    816: "Single-Sentence Oracle",
    817: "Single-Sentence Oracle",
    818: "Single-Sentence Oracle",
    819: "Single-Sentence Oracle",
    820: "Single-Sentence Oracle",
    821: "Single-Sentence Oracle",
    822: "Single-Sentence Oracle",
    823: "Single-Sentence Oracle",
    824: "Single-Sentence Oracle",
    825: "Single-Sentence Oracle",
    826: "Single-Sentence Oracle",
}


def _heroes_for(cid: int) -> list[str]:
    return [name for name, meta in HERO_ENGINES.items() if cid in meta["capability_ids"]]


def _primary_hero_for(cid: int) -> str | None:
    hits = _heroes_for(cid)
    if hits:
        return hits[0]
    if cid in _BATCH01_FALLBACK:
        return _BATCH01_FALLBACK[cid]
    if cid in _BATCH02_FALLBACK:
        return _BATCH02_FALLBACK[cid]
    return (_BATCH03_FALLBACK.get(cid
        or _BATCH17_FALLBACK.get(cid) or _BATCH19_FALLBACK.get(cid)
        or _BATCH21_FALLBACK.get(cid) or _BATCH23_FALLBACK.get(cid)
        or _BATCH25_FALLBACK.get(cid) or _BATCH27_FALLBACK.get(cid) or _BATCH29_FALLBACK.get(cid) or _BATCH31_FALLBACK.get(cid) or _BATCH33_FALLBACK.get(cid)) or _BATCH05_FALLBACK.get(cid
        or _BATCH17_FALLBACK.get(cid) or _BATCH19_FALLBACK.get(cid)
        or _BATCH21_FALLBACK.get(cid) or _BATCH23_FALLBACK.get(cid)
        or _BATCH25_FALLBACK.get(cid) or _BATCH27_FALLBACK.get(cid) or _BATCH29_FALLBACK.get(cid) or _BATCH31_FALLBACK.get(cid) or _BATCH33_FALLBACK.get(cid)) or _BATCH07_FALLBACK.get(cid
        or _BATCH17_FALLBACK.get(cid) or _BATCH19_FALLBACK.get(cid)
        or _BATCH21_FALLBACK.get(cid) or _BATCH23_FALLBACK.get(cid)
        or _BATCH25_FALLBACK.get(cid) or _BATCH27_FALLBACK.get(cid))
        or _BATCH11_FALLBACK.get(cid
        or _BATCH17_FALLBACK.get(cid) or _BATCH19_FALLBACK.get(cid)
        or _BATCH21_FALLBACK.get(cid) or _BATCH23_FALLBACK.get(cid)
        or _BATCH25_FALLBACK.get(cid) or _BATCH27_FALLBACK.get(cid) or _BATCH29_FALLBACK.get(cid) or _BATCH31_FALLBACK.get(cid) or _BATCH33_FALLBACK.get(cid)) or _BATCH13_FALLBACK.get(cid
        or _BATCH17_FALLBACK.get(cid) or _BATCH19_FALLBACK.get(cid)
        or _BATCH21_FALLBACK.get(cid) or _BATCH23_FALLBACK.get(cid)
        or _BATCH25_FALLBACK.get(cid) or _BATCH27_FALLBACK.get(cid) or _BATCH29_FALLBACK.get(cid) or _BATCH31_FALLBACK.get(cid) or _BATCH33_FALLBACK.get(cid)) or _BATCH15_FALLBACK.get(cid
        or _BATCH17_FALLBACK.get(cid) or _BATCH19_FALLBACK.get(cid)
        or _BATCH21_FALLBACK.get(cid) or _BATCH23_FALLBACK.get(cid)
        or _BATCH25_FALLBACK.get(cid) or _BATCH27_FALLBACK.get(cid))
        or _BATCH17_FALLBACK.get(cid) or _BATCH19_FALLBACK.get(cid)
        or _BATCH21_FALLBACK.get(cid) or _BATCH23_FALLBACK.get(cid)
        or _BATCH25_FALLBACK.get(cid) or _BATCH27_FALLBACK.get(cid) or _BATCH29_FALLBACK.get(cid) or _BATCH31_FALLBACK.get(cid) or _BATCH33_FALLBACK.get(cid))


def hero_binding_for(cid: int) -> dict[str, Any]:
    """Return primary_hero, hero_entry_path, hero_binding_status for register."""
    heroes = _heroes_for(cid)
    if not heroes:
        fb = (
            _BATCH01_FALLBACK.get(cid)
            or _BATCH02_FALLBACK.get(cid)
            or _BATCH03_FALLBACK.get(cid)
            or _BATCH05_FALLBACK.get(cid)
            or _BATCH07_FALLBACK.get(cid)
            or _BATCH11_FALLBACK.get(cid)
            or _BATCH13_FALLBACK.get(cid)
            or _BATCH15_FALLBACK.get(cid)
            or _BATCH17_FALLBACK.get(cid)
            or _BATCH19_FALLBACK.get(cid)
            or _BATCH21_FALLBACK.get(cid)
            or _BATCH23_FALLBACK.get(cid)
            or _BATCH25_FALLBACK.get(cid)
            or _BATCH27_FALLBACK.get(cid)
            or _BATCH29_FALLBACK.get(cid)
            or _BATCH31_FALLBACK.get(cid)
            or _BATCH33_FALLBACK.get(cid)
        )
        if fb:
            heroes = [fb]
    hero = heroes[0] if heroes else None
    if not hero:
        return {
            "primary_hero": None,
            "secondary_heroes": [],
            "hero_entry_path": None,
            "hero_ui_path": None,
            "hero_binding_status": "UNBOUND",
        }
    meta = HERO_ENGINES[hero]
    cap_path = f"/api/cap646/{cid}/execute"
    entry = meta["live_endpoint"]["path"]
    return {
        "primary_hero": hero,
        "secondary_heroes": heroes[1:],
        "hero_entry_path": f"{entry} → {cap_path}",
        "hero_ui_path": meta.get("ui_path", "/cap646"),
        "hero_binding_status": "BOUND",
        "cap646_execute_path": cap_path,
    }


def enrich_binding_row(cid: int, row: dict[str, Any]) -> dict[str, Any]:
    binding = hero_binding_for(cid)
    row.update(binding)
    if binding["hero_binding_status"] == "UNBOUND" and row.get("status") == "COMPLETE_V6":
        blockers = list(row.get("blocker") or [])
        blockers.append("hero_binding:UNBOUND")
        row["status"] = "PARTIAL"
        row["blocker"] = blockers
    return row
