"""True v6 institutional Definition of Done — aligned with governing standard file.

Reference: governing-sources-population/BLACKDARK_Institutional_Capability_Standard_2026_v6(1).md
§2.1, §34, §1170–1171, §139.5

This module is intentionally stricter than cap646.v6_strict_dod:
- Rejects keyword/semantic-track bulk routing as PASS_ENGINEERING
- Requires semantic appropriateness (goal-specific payload), not success=true alone
- Requires per-capability or dedicated-batch test traceability
- Does not auto-pass regression/performance/data-quality gates
"""

from __future__ import annotations

import re
from functools import lru_cache
from pathlib import Path
from typing import Any

from cap646.catalog import catalog_by_id, is_duplicate, is_external
from cap646.backend_registry import resolve_binding, is_generic_surface
from cap646.runtime import execute_capability

ROOT = Path(__file__).resolve().parent.parent

# Binding sources that v6 §1170–1171 treat as insufficient alone (generic routing)
_SUPERFICIAL_BINDING_SOURCES = frozenset(
    {
        "batch_range_production_spine",
        "track_default",
        "platform_codepath",
        "capability_keyword",
        "capability_semantic_map",
        "extension_keyword",
        "extension_track_default",
    }
)

# Prefixes for track-default semantic fallbacks generated by backend_registry
_SEMANTIC_TRACK_PREFIX = "semantic_track_"

_DEDICATED_BINDING_SOURCES = frozenset(
    {
        "explicit_option_a",
        "batch01_production_spine_ssot",
        "batch02_production_spine_ssot",
        "batch03_production_spine_ssot",
        "gap_matrix_component",
        "extension_id",
        "free_tier_explicit",
        "cap978_extension_registry",
    }
)

_STUB_STATUSES = frozenset({"STUB", "STUB_TEMPLATE", "NOT_IMPLEMENTED", "PLACEHOLDER", "NOT_COMPLETE"})


@lru_cache(maxsize=1)
def _semantic_map_ids() -> frozenset[int]:
    import json

    path = ROOT / "cap646" / "capability_semantic_map.json"
    if not path.exists():
        return frozenset()
    data = json.loads(path.read_text(encoding="utf-8"))
    generated = data.get("generated") or {}
    return frozenset(int(k) for k in generated.keys())


@lru_cache(maxsize=1)
def _dedicated_entrypoint_ids() -> frozenset[int]:
    ids: set[int] = set()
    for path in (ROOT / "cap646").glob("batch*_dedicated.py"):
        text = path.read_text(encoding="utf-8", errors="ignore")
        for match in re.finditer(r"[_]cap(\d{1,3})", text):
            ids.add(int(match.group(1)))
        m = re.search(r"BATCH\d{2}_DEDICATED_IDS:\s*frozenset\(\{([^}]+)\}\)", text)
        if m:
            for token in re.findall(r"\d+", m.group(1)):
                val = int(token)
                if 1 <= val <= 826:
                    ids.add(val)
    return frozenset(ids)


@lru_cache(maxsize=1)
def _test_referenced_ids() -> frozenset[int]:
    ids: set[int] = set()
    tests_root = ROOT / "tests"
    if tests_root.is_dir():
        pattern = re.compile(
            r"capability_id[\"']?\s*[:=]\s*(\d+)|cap_(\d{3})|test_cap_?(\d{1,3})"
        )
        for path in tests_root.rglob("*.py"):
            text = path.read_text(encoding="utf-8", errors="ignore")
            for match in pattern.finditer(text):
                for group in match.groups():
                    if not group:
                        continue
                    val = int(group)
                    if 1 <= val <= 826:
                        ids.add(val)
    import importlib

    try:
        from bd_platform.free_tier_capabilities import FREE_TIER_BASE_IDS

        ids.update(FREE_TIER_BASE_IDS)
    except Exception:
        pass
    try:
        from cap646.batch01_production import LEGACY_BATCH01_EXTENSION_IDS, BATCH01_IDS

        ids.update(LEGACY_BATCH01_EXTENSION_IDS)
        ids.update(BATCH01_IDS)
    except Exception:
        pass

    for mod_name in (
        "cap646.batch01_dedicated",
        "cap646.batch02_dedicated",
        "cap646.batch03_dedicated",
    ):
        try:
            mod = importlib.import_module(mod_name)
        except ImportError:
            continue
        for attr in dir(mod):
            if attr.endswith("_DEDICATED_IDS"):
                ids.update(int(x) for x in getattr(mod, attr))

    for rel in (
        "tests/cap646/test_batch_range_dedicated.py",
        "tests/cap646/test_batch01_dedicated.py",
        "tests/cap646/test_batch02_dedicated.py",
        "tests/cap646/test_batch03_prep_dedicated.py",
        "tests/cap646/test_batch01_production.py",
    ):
        path = ROOT / rel
        if not path.is_file():
            continue
        text = path.read_text(encoding="utf-8", errors="ignore")
        for m in re.finditer(r"DEDICATED_IDS\s*=\s*\[([^\]]+)\]|parametrize\([^)]*(\d+)", text):
            chunk = m.group(1) or m.group(2) or ""
            for token in re.findall(r"\d+", chunk):
                val = int(token)
                if 1 <= val <= 826:
                    ids.add(val)
        for m in re.finditer(r"@pytest\.mark\.parametrize\([^\]]*\[([^\]]+)\]", text):
            for token in re.findall(r"\d+", m.group(1)):
                val = int(token)
                if 1 <= val <= 826:
                    ids.add(val)
    return frozenset(ids)


def _payload(result: dict[str, Any]) -> dict[str, Any]:
    inner = result.get("result")
    if isinstance(inner, dict):
        return inner
    if isinstance(result, dict):
        return result
    return {}


def _is_superficial_binding(binding: Any) -> bool:
    src = binding.source or ""
    if src in {
        "explicit_option_a",
        "batch01_production_spine_ssot",
        "batch02_production_spine_ssot",
        "batch03_production_spine_ssot",
    }:
        return False
    if src in _SUPERFICIAL_BINDING_SOURCES:
        return True
    if src.startswith(_SEMANTIC_TRACK_PREFIX):
        return True
    if binding.capability_id in _semantic_map_ids() and src not in _DEDICATED_BINDING_SOURCES:
        return True
    return False


def _name_tokens(name: str) -> list[str]:
    stop = {"and", "the", "for", "with", "from", "capability", "extension", "intelligence", "system"}
    return [t for t in re.findall(r"[a-z]{3,}", name.lower()) if t not in stop]


def _gate_functional_appropriateness_true(name: str, payload: dict[str, Any], binding: Any) -> tuple[bool, str]:
    if _is_superficial_binding(binding):
        return False, "superficial_binding_source"

    nl = name.lower()
    keys = " ".join(str(k).lower() for k in payload.keys())
    values = " ".join(str(v).lower() for v in payload.values() if isinstance(v, (str, int, float)))

    # Reject obvious cross-purpose payloads (v6 §2.1.3)
    if "connector" in nl or "bi " in nl:
        if any(k in payload for k in ("viral", "unconditional_go", "billing_provider")):
            return False, "bi_connector_wrong_payload"
        if "bi_connectors" in keys or "bi_connectors" in values:
            return True, "bi_connector_payload"

    tokens = _name_tokens(name)
    if not tokens:
        return True, "no_name_tokens"

    matched = sum(1 for t in tokens if t in keys or t in values or t in nl)
    if matched == 0 and binding.source not in _DEDICATED_BINDING_SOURCES:
        return False, "payload_not_semantically_aligned"
    if matched == 0 and len(tokens) >= 2:
        return False, "dedicated_binding_but_generic_payload"

    return True, "semantic_match"


def _gate_traceability_true(capability_id: int, binding: Any) -> tuple[bool, str]:
    if capability_id in _dedicated_entrypoint_ids():
        return True, "dedicated_entrypoint"
    if capability_id in _test_referenced_ids():
        return True, "test_reference"
    if binding.source in {
        "batch01_production_spine_ssot",
        "batch02_production_spine_ssot",
        "batch03_production_spine_ssot",
        "explicit_option_a",
    }:
        return True, "batch_spine_ssot"
    return False, "no_dedicated_handler_or_test"


def _gate_regression_true(capability_id: int) -> tuple[bool, str]:
    if capability_id in _test_referenced_ids():
        return True, "tests_present"
    return False, "no_per_capability_regression_test"


def _gate_performance_true(result: dict[str, Any]) -> tuple[bool, str]:
    if result.get("latency_ms") is not None or result.get("performance_gate"):
        return True, "perf_metadata"
    data = result if isinstance(result, dict) else {}
    inner = data.get("result") if isinstance(data.get("result"), dict) else data
    for key in (data, inner):
        if isinstance(key, dict) and (key.get("latency_ms") is not None or key.get("performance_gate")):
            return True, "perf_metadata_nested"
    return False, "no_performance_evidence"


def _gate_data_quality_true(result: dict[str, Any], payload: dict[str, Any]) -> tuple[bool, str]:
    if any(k in payload for k in ("provenance", "provenance_score", "data_provenance", "freshness")):
        return True, "provenance_present"
    if result.get("data_provenance"):
        return True, "result_provenance"
    if "provenance" in str(result.get("backend_module", "")):
        return True, "provenance_module"
    domain = payload.get("domain_result")
    if isinstance(domain, dict) and any(k in domain for k in ("provenance", "provenance_score", "freshness")):
        return True, "domain_provenance"
    return False, "no_data_quality_evidence"


async def verify_v6_true_institutional(
    capability_id: int,
    *,
    user: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Run true v6 institutional gates per governing standard §2.1 + §34."""
    row = catalog_by_id().get(capability_id, {})
    name = row.get("capability", "")

    if is_external(capability_id):
        return {
            "capability_id": capability_id,
            "verdict": "EXTERNAL_BLOCKED",
            "PASS_ENGINEERING": False,
            "reason": "external_blocked",
        }

    if is_duplicate(capability_id):
        return {
            "capability_id": capability_id,
            "verdict": "CANONICALLY_COVERED",
            "PASS_ENGINEERING": True,
            "reason": "duplicate_canonical",
        }

    binding = resolve_binding(capability_id)
    result = await execute_capability(
        capability_id,
        skip_entitlement=True,
        user=user or {"email": "v6-true-audit@blackdark.local", "tier": "whale"},
        params={"symbol": "BTC", "tier": "whale"},
    )
    payload = _payload(result)

    g03_ok, g03_reason = _gate_functional_appropriateness_true(name, payload, binding)
    g04_ok, g04_reason = _gate_traceability_true(capability_id, binding)
    g06_ok, g06_reason = _gate_regression_true(capability_id)
    g08_ok, g08_reason = _gate_performance_true(result)
    g11_ok, g11_reason = _gate_data_quality_true(result, payload)

    superficial = _is_superficial_binding(binding)
    stub_hit = result.get("error") in {"demo_only", "mock_only", "stub_only"} or str(
        payload.get("status") or ""
    ).upper() in _STUB_STATUSES

    gates = {
        "G01_functional_completeness": bool(result.get("success")) and bool(result.get("backend_module")) and not stub_hit,
        "G02_functional_correctness": bool(result.get("success")) and result.get("backend_module") == binding.module and not superficial,
        "G03_functional_appropriateness": g03_ok,
        "G04_requirements_traceability": g04_ok,
        "G05_integration_correctness": bool(result.get("binding_source")) and not result.get("failover_module"),
        "G06_regression_safety": g06_ok,
        "G07_security_gate": result.get("error") not in {"demo_only", "mock_only", "stub_only"},
        "G08_performance_gate": g08_ok,
        "G09_reliability_gate": result.get("success") is True,
        "G10_observability_gate": result.get("evidence_class") is not None or result.get("classification") is not None,
        "G11_data_quality_gate": g11_ok,
        "G12_user_path_gate": bool(result.get("surface")) and not is_generic_surface(result.get("surface")),
        "G13_evidence_gate": bool(result.get("compliance_footer") or result.get("evidence_metadata")),
    }

    failed = [k for k, v in gates.items() if not v]
    pass_eng = len(failed) == 0

    return {
        "capability_id": capability_id,
        "capability": name,
        "track": row.get("track"),
        "verdict": "PASS_ENGINEERING" if pass_eng else "NOT_COMPLETE",
        "PASS_ENGINEERING": pass_eng,
        "gates": gates,
        "failed_gates": failed,
        "binding_source": binding.source,
        "backend_module": result.get("backend_module"),
        "superficial_binding": superficial,
        "gate_reasons": {
            "G03": g03_reason,
            "G04": g04_reason,
            "G06": g06_reason,
            "G08": g08_reason,
            "G11": g11_reason,
        },
    }
