"""Batch16 (751–800) pre-build classification — categories A–H only."""

from __future__ import annotations

from typing import Any

PREBUILD_CLASSIFICATION: dict[int, str] = {
    751: "E. CANONICAL_DUPLICATE_REUSE",
    752: "E. CANONICAL_DUPLICATE_REUSE",
    753: "E. CANONICAL_DUPLICATE_REUSE",
    754: "E. CANONICAL_DUPLICATE_REUSE",
    755: "E. CANONICAL_DUPLICATE_REUSE",
    756: "E. CANONICAL_DUPLICATE_REUSE",
    757: "E. CANONICAL_DUPLICATE_REUSE",
    758: "E. CANONICAL_DUPLICATE_REUSE",
    759: "E. CANONICAL_DUPLICATE_REUSE",
    760: "E. CANONICAL_DUPLICATE_REUSE",
    761: "E. CANONICAL_DUPLICATE_REUSE",
    762: "E. CANONICAL_DUPLICATE_REUSE",
    763: "E. CANONICAL_DUPLICATE_REUSE",
    764: "E. CANONICAL_DUPLICATE_REUSE",
    765: "E. CANONICAL_DUPLICATE_REUSE",
    766: "E. CANONICAL_DUPLICATE_REUSE",
    767: "E. CANONICAL_DUPLICATE_REUSE",
    768: "E. CANONICAL_DUPLICATE_REUSE",
    769: "E. CANONICAL_DUPLICATE_REUSE",
    770: "E. CANONICAL_DUPLICATE_REUSE",
    771: "E. CANONICAL_DUPLICATE_REUSE",
    772: "E. CANONICAL_DUPLICATE_REUSE",
    773: "E. CANONICAL_DUPLICATE_REUSE",
    774: "E. CANONICAL_DUPLICATE_REUSE",
    775: "E. CANONICAL_DUPLICATE_REUSE",
    776: "E. CANONICAL_DUPLICATE_REUSE",
    777: "E. CANONICAL_DUPLICATE_REUSE",
    778: "E. CANONICAL_DUPLICATE_REUSE",
    779: "E. CANONICAL_DUPLICATE_REUSE",
    780: "E. CANONICAL_DUPLICATE_REUSE",
    781: "E. CANONICAL_DUPLICATE_REUSE",
    782: "E. CANONICAL_DUPLICATE_REUSE",
    783: "E. CANONICAL_DUPLICATE_REUSE",
    784: "E. CANONICAL_DUPLICATE_REUSE",
    785: "E. CANONICAL_DUPLICATE_REUSE",
    786: "E. CANONICAL_DUPLICATE_REUSE",
    787: "E. CANONICAL_DUPLICATE_REUSE",
    788: "E. CANONICAL_DUPLICATE_REUSE",
    789: "E. CANONICAL_DUPLICATE_REUSE",
    790: "E. CANONICAL_DUPLICATE_REUSE",
    791: "E. CANONICAL_DUPLICATE_REUSE",
    792: "E. CANONICAL_DUPLICATE_REUSE",
    793: "E. CANONICAL_DUPLICATE_REUSE",
    794: "E. CANONICAL_DUPLICATE_REUSE",
    795: "E. CANONICAL_DUPLICATE_REUSE",
    796: "E. CANONICAL_DUPLICATE_REUSE",
    797: "E. CANONICAL_DUPLICATE_REUSE",
    798: "E. CANONICAL_DUPLICATE_REUSE",
    799: "E. CANONICAL_DUPLICATE_REUSE",
    800: "E. CANONICAL_DUPLICATE_REUSE",
}

CANONICAL_DUPLICATE_TARGETS: dict[int, int] = {
    751: 484,
    752: 485,
    753: 486,
    754: 487,
    755: 488,
    756: 489,
    757: 490,
    758: 491,
    759: 492,
    760: 493,
    761: 494,
    762: 495,
    763: 496,
    764: 497,
    765: 498,
    766: 499,
    767: 500,
    768: 501,
    769: 502,
    770: 503,
    771: 504,
    772: 505,
    773: 506,
    774: 507,
    775: 508,
    776: 509,
    777: 510,
    778: 511,
    779: 512,
    780: 513,
    781: 514,
    782: 515,
    783: 516,
    784: 517,
    785: 518,
    786: 519,
    787: 520,
    788: 521,
    789: 522,
    790: 523,
    791: 524,
    792: 525,
    793: 526,
    794: 527,
    795: 528,
    796: 529,
    797: 530,
    798: 531,
    799: 532,
    800: 533,
}

PREBUILD_EVIDENCE: dict[int, dict[str, Any]] = {
    751: {"canonical_capability_id": 484, "evidence": "OHLCV Data delegates to bd_platform.defi_yield_intelligence_layer.ohlcv_data_484"},
    752: {"canonical_capability_id": 485, "evidence": "Derivatives Data delegates to bd_platform.defi_yield_intelligence_layer.derivatives_data_485"},
    753: {"canonical_capability_id": 486, "evidence": "Open Interest Data delegates to bd_platform.defi_yield_intelligence_layer.open_interest_data_486"},
    754: {"canonical_capability_id": 487, "evidence": "Funding Rate Data delegates to bd_platform.defi_yield_intelligence_layer.funding_rate_data_487"},
    755: {"canonical_capability_id": 488, "evidence": "Index Data delegates to bd_platform.defi_yield_intelligence_layer.index_data_488"},
    756: {"canonical_capability_id": 489, "evidence": "Reference Pricing delegates to bd_platform.defi_yield_intelligence_layer.reference_pricing_489"},
    757: {"canonical_capability_id": 490, "evidence": "Exchange Metadata delegates to bd_platform.defi_yield_intelligence_layer.exchange_metadata_490"},
    758: {"canonical_capability_id": 491, "evidence": "Asset Metadata delegates to bd_platform.defi_yield_intelligence_layer.asset_metadata_491"},
    759: {"canonical_capability_id": 492, "evidence": "Historical Market Archive delegates to bd_platform.defi_yield_intelligence_layer.historical_market_archive_492"},
    760: {"canonical_capability_id": 493, "evidence": "Real-Time Streams delegates to bd_platform.defi_yield_intelligence_layer.real_time_streams_493"},
    761: {"canonical_capability_id": 494, "evidence": "Market Aggregates delegates to bd_platform.defi_yield_intelligence_layer.market_aggregates_494"},
    762: {"canonical_capability_id": 495, "evidence": "Liquidity Analytics delegates to bd_platform.defi_yield_intelligence_layer.liquidity_analytics_495"},
    763: {"canonical_capability_id": 496, "evidence": "Volatility Analytics delegates to bd_platform.defi_yield_intelligence_layer.volatility_analytics_496"},
    764: {"canonical_capability_id": 497, "evidence": "Market Cap / Supply delegates to bd_platform.defi_yield_intelligence_layer.market_cap_supply_497"},
    765: {"canonical_capability_id": 498, "evidence": "ETF / ETP Data delegates to bd_platform.defi_yield_intelligence_layer.etf_etp_data_498"},
    766: {"canonical_capability_id": 499, "evidence": "API Coverage Registry delegates to bd_platform.defi_yield_intelligence_layer.api_coverage_registry_499"},
    767: {"canonical_capability_id": 500, "evidence": "Data Quality & Normalization delegates to bd_platform.defi_yield_intelligence_layer.data_quality_normalization_500"},
    768: {"canonical_capability_id": 501, "evidence": "Institutional Delivery delegates to bd_platform.institutional_delivery_intelligence_layer.institutional_delivery_501"},
    769: {"canonical_capability_id": 502, "evidence": "Benchmark Administration Metadata delegates to bd_platform.institutional_delivery_intelligence_layer.benchmark_administration_metadata_502"},
    770: {"canonical_capability_id": 503, "evidence": "Cross-Market Data Intelligence delegates to bd_platform.institutional_delivery_intelligence_layer.cross_market_data_intelligence_503"},
    771: {"canonical_capability_id": 504, "evidence": "Unified Exchange Connector Layer delegates to bd_platform.institutional_delivery_intelligence_layer.unified_exchange_connector_layer_504"},
    772: {"canonical_capability_id": 505, "evidence": "Tick Trade Data delegates to bd_platform.institutional_delivery_intelligence_layer.tick_trade_data_505"},
    773: {"canonical_capability_id": 506, "evidence": "Quote Data delegates to bd_platform.institutional_delivery_intelligence_layer.quote_data_506"},
    774: {"canonical_capability_id": 507, "evidence": "OHLCV delegates to bd_platform.institutional_delivery_intelligence_layer.ohlcv_507"},
    775: {"canonical_capability_id": 508, "evidence": "L1 Order Book delegates to bd_platform.institutional_delivery_intelligence_layer.l1_order_book_508"},
    776: {"canonical_capability_id": 509, "evidence": "L2 Order Book delegates to bd_platform.institutional_delivery_intelligence_layer.l2_order_book_509"},
    777: {"canonical_capability_id": 510, "evidence": "L3 Order Book delegates to bd_platform.institutional_delivery_intelligence_layer.l3_order_book_510"},
    778: {"canonical_capability_id": 511, "evidence": "Options Market Data delegates to bd_platform.institutional_delivery_intelligence_layer.options_market_data_511"},
    779: {"canonical_capability_id": 512, "evidence": "Funding / OI / Liquidation Metrics delegates to bd_platform.institutional_delivery_intelligence_layer.funding_oi_liquidation_metrics_512"},
    780: {"canonical_capability_id": 513, "evidence": "Asset & Symbol Metadata delegates to bd_platform.institutional_delivery_intelligence_layer.asset_symbol_metadata_513"},
    781: {"canonical_capability_id": 514, "evidence": "Historical Flat Files delegates to bd_platform.institutional_delivery_intelligence_layer.historical_flat_files_514"},
    782: {"canonical_capability_id": 515, "evidence": "REST API delegates to bd_platform.institutional_delivery_intelligence_layer.rest_api_515"},
    783: {"canonical_capability_id": 516, "evidence": "WebSocket Streaming delegates to bd_platform.institutional_delivery_intelligence_layer.websocket_streaming_516"},
    784: {"canonical_capability_id": 517, "evidence": "FIX Connectivity delegates to bd_platform.institutional_delivery_intelligence_layer.fix_connectivity_517"},
    785: {"canonical_capability_id": 518, "evidence": "MCP for AI delegates to bd_platform.institutional_delivery_intelligence_layer.mcp_for_ai_518"},
    786: {"canonical_capability_id": 519, "evidence": "Exchange Rates / VWAP delegates to bd_platform.institutional_delivery_intelligence_layer.exchange_rates_vwap_519"},
    787: {"canonical_capability_id": 520, "evidence": "Indexes delegates to bd_platform.institutional_delivery_intelligence_layer.indexes_520"},
    788: {"canonical_capability_id": 521, "evidence": "Volatility Index delegates to bd_platform.institutional_delivery_intelligence_layer.volatility_index_521"},
    789: {"canonical_capability_id": 522, "evidence": "EMS Integration Boundary delegates to bd_platform.institutional_delivery_intelligence_layer.ems_integration_boundary_522"},
    790: {"canonical_capability_id": 523, "evidence": "Data Health / SLA Monitoring delegates to bd_platform.institutional_delivery_intelligence_layer.data_health_sla_monitoring_523"},
    791: {"canonical_capability_id": 524, "evidence": "Symbol Mapping Engine delegates to bd_platform.institutional_delivery_intelligence_layer.symbol_mapping_engine_524"},
    792: {"canonical_capability_id": 525, "evidence": "Cross-Venue Data Quality Score delegates to bd_platform.heroes_capability_layer.strategy_backtesting_525"},
    793: {"canonical_capability_id": 526, "evidence": "AI Market Data Grounding Layer delegates to bd_platform.institutional_delivery_intelligence_layer.ai_market_data_grounding_layer_526"},
    794: {"canonical_capability_id": 527, "evidence": "Liquidation Heatmap delegates to bd_platform.institutional_delivery_intelligence_layer.liquidation_heatmap_527"},
    795: {"canonical_capability_id": 528, "evidence": "Liquidation Levels delegates to bd_platform.market_rankings.market_rankings"},
    796: {"canonical_capability_id": 529, "evidence": "Liquidation Cascade Model delegates to bd_platform.institutional_delivery_intelligence_layer.liquidation_cascade_model_529"},
    797: {"canonical_capability_id": 530, "evidence": "Global Liquidation Metrics delegates to bd_platform.institutional_delivery_intelligence_layer.global_liquidation_metrics_530"},
    798: {"canonical_capability_id": 531, "evidence": "Open Interest delegates to bd_platform.institutional_delivery_intelligence_layer.open_interest_531"},
    799: {"canonical_capability_id": 532, "evidence": "Funding Rates delegates to bd_platform.institutional_delivery_intelligence_layer.funding_rates_532"},
    800: {"canonical_capability_id": 533, "evidence": "Order Flow Intelligence delegates to bd_platform.institutional_delivery_intelligence_layer.order_flow_intelligence_533"},
}

def verify_prebuild_classification() -> dict[str, Any]:
    ids = sorted(PREBUILD_CLASSIFICATION)
    return {
        "ok": len(ids) == 50 and len(set(ids)) == 50,
        "count": len(ids),
        "unique": len(set(ids)),
    }
