"""Batch15 (701–750) pre-build classification — categories A–H only."""

from __future__ import annotations

from typing import Any

PREBUILD_CLASSIFICATION: dict[int, str] = {
    701: "E. CANONICAL_DUPLICATE_REUSE",
    702: "E. CANONICAL_DUPLICATE_REUSE",
    703: "E. CANONICAL_DUPLICATE_REUSE",
    704: "E. CANONICAL_DUPLICATE_REUSE",
    705: "E. CANONICAL_DUPLICATE_REUSE",
    706: "E. CANONICAL_DUPLICATE_REUSE",
    707: "E. CANONICAL_DUPLICATE_REUSE",
    708: "E. CANONICAL_DUPLICATE_REUSE",
    709: "E. CANONICAL_DUPLICATE_REUSE",
    710: "E. CANONICAL_DUPLICATE_REUSE",
    711: "E. CANONICAL_DUPLICATE_REUSE",
    712: "E. CANONICAL_DUPLICATE_REUSE",
    713: "E. CANONICAL_DUPLICATE_REUSE",
    714: "E. CANONICAL_DUPLICATE_REUSE",
    715: "E. CANONICAL_DUPLICATE_REUSE",
    716: "E. CANONICAL_DUPLICATE_REUSE",
    717: "E. CANONICAL_DUPLICATE_REUSE",
    718: "E. CANONICAL_DUPLICATE_REUSE",
    719: "E. CANONICAL_DUPLICATE_REUSE",
    720: "E. CANONICAL_DUPLICATE_REUSE",
    721: "E. CANONICAL_DUPLICATE_REUSE",
    722: "E. CANONICAL_DUPLICATE_REUSE",
    723: "E. CANONICAL_DUPLICATE_REUSE",
    724: "E. CANONICAL_DUPLICATE_REUSE",
    725: "E. CANONICAL_DUPLICATE_REUSE",
    726: "E. CANONICAL_DUPLICATE_REUSE",
    727: "E. CANONICAL_DUPLICATE_REUSE",
    728: "E. CANONICAL_DUPLICATE_REUSE",
    729: "E. CANONICAL_DUPLICATE_REUSE",
    730: "E. CANONICAL_DUPLICATE_REUSE",
    731: "E. CANONICAL_DUPLICATE_REUSE",
    732: "E. CANONICAL_DUPLICATE_REUSE",
    733: "E. CANONICAL_DUPLICATE_REUSE",
    734: "E. CANONICAL_DUPLICATE_REUSE",
    735: "E. CANONICAL_DUPLICATE_REUSE",
    736: "E. CANONICAL_DUPLICATE_REUSE",
    737: "E. CANONICAL_DUPLICATE_REUSE",
    738: "E. CANONICAL_DUPLICATE_REUSE",
    739: "E. CANONICAL_DUPLICATE_REUSE",
    740: "E. CANONICAL_DUPLICATE_REUSE",
    741: "E. CANONICAL_DUPLICATE_REUSE",
    742: "E. CANONICAL_DUPLICATE_REUSE",
    743: "E. CANONICAL_DUPLICATE_REUSE",
    744: "E. CANONICAL_DUPLICATE_REUSE",
    745: "E. CANONICAL_DUPLICATE_REUSE",
    746: "E. CANONICAL_DUPLICATE_REUSE",
    747: "E. CANONICAL_DUPLICATE_REUSE",
    748: "E. CANONICAL_DUPLICATE_REUSE",
    749: "E. CANONICAL_DUPLICATE_REUSE",
    750: "E. CANONICAL_DUPLICATE_REUSE",
}

CANONICAL_DUPLICATE_TARGETS: dict[int, int] = {
    701: 434,
    702: 435,
    703: 436,
    704: 437,
    705: 438,
    706: 439,
    707: 440,
    708: 441,
    709: 442,
    710: 443,
    711: 444,
    712: 445,
    713: 446,
    714: 447,
    715: 448,
    716: 449,
    717: 450,
    718: 451,
    719: 452,
    720: 453,
    721: 454,
    722: 455,
    723: 456,
    724: 457,
    725: 458,
    726: 459,
    727: 460,
    728: 461,
    729: 462,
    730: 463,
    731: 464,
    732: 465,
    733: 466,
    734: 467,
    735: 468,
    736: 469,
    737: 470,
    738: 471,
    739: 472,
    740: 473,
    741: 474,
    742: 475,
    743: 476,
    744: 477,
    745: 478,
    746: 479,
    747: 480,
    748: 481,
    749: 482,
    750: 483,
}

PREBUILD_EVIDENCE: dict[int, dict[str, Any]] = {
    701: {"canonical_capability_id": 434, "evidence": "Revenue / Fees / Economic Activity delegates to bd_platform.defi_yield_intelligence_layer.revenue_fees_economic_activity_434"},
    702: {"canonical_capability_id": 435, "evidence": "Cross-Market Research Copilot delegates to bd_platform.defi_yield_intelligence_layer.cross_market_research_copilot_435"},
    703: {"canonical_capability_id": 436, "evidence": "Investment Thesis Scoring delegates to bd_platform.defi_yield_intelligence_layer.investment_thesis_scoring_436"},
    704: {"canonical_capability_id": 437, "evidence": "DeFi Risk Radar delegates to bd_platform.defi_yield_intelligence_layer.defi_risk_radar_437"},
    705: {"canonical_capability_id": 438, "evidence": "Lending Market Risk delegates to bd_platform.defi_yield_intelligence_layer.lending_market_risk_438"},
    706: {"canonical_capability_id": 439, "evidence": "Collateral Risk delegates to bd_platform.defi_yield_intelligence_layer.collateral_risk_439"},
    707: {"canonical_capability_id": 440, "evidence": "Liquidation Risk delegates to bd_platform.defi_yield_intelligence_layer.liquidation_risk_440"},
    708: {"canonical_capability_id": 441, "evidence": "Oracle Risk delegates to bd_platform.defi_yield_intelligence_layer.oracle_risk_441"},
    709: {"canonical_capability_id": 442, "evidence": "Liquidity Risk delegates to bd_platform.defi_yield_intelligence_layer.liquidity_risk_442"},
    710: {"canonical_capability_id": 443, "evidence": "Protocol Exploit Intelligence delegates to bd_platform.defi_yield_intelligence_layer.protocol_exploit_intelligence_443"},
    711: {"canonical_capability_id": 444, "evidence": "Stablecoin Risk Intelligence delegates to bd_platform.defi_yield_intelligence_layer.stablecoin_risk_intelligence_444"},
    712: {"canonical_capability_id": 445, "evidence": "DeFi Strategy Risk delegates to bd_platform.defi_yield_intelligence_layer.defi_strategy_risk_445"},
    713: {"canonical_capability_id": 446, "evidence": "Real-Time Risk Alerts delegates to bd_platform.defi_yield_intelligence_layer.real_time_risk_alerts_446"},
    714: {"canonical_capability_id": 447, "evidence": "DAO Treasury Risk delegates to bd_platform.defi_yield_intelligence_layer.dao_treasury_risk_447"},
    715: {"canonical_capability_id": 448, "evidence": "Institutional Risk API delegates to bd_platform.defi_yield_intelligence_layer.institutional_risk_api_448"},
    716: {"canonical_capability_id": 449, "evidence": "Curated On-Chain Dashboards delegates to bd_platform.defi_yield_intelligence_layer.curated_on_chain_dashboards_449"},
    717: {"canonical_capability_id": 450, "evidence": "Narrative-Driven Research delegates to bd_platform.defi_yield_intelligence_layer.narrative_driven_research_450"},
    718: {"canonical_capability_id": 451, "evidence": "Protocol Dominance delegates to bd_platform.defi_yield_intelligence_layer.protocol_dominance_451"},
    719: {"canonical_capability_id": 452, "evidence": "Aave Multi-Chain Analytics delegates to bd_platform.defi_yield_intelligence_layer.aave_multi_chain_analytics_452"},
    720: {"canonical_capability_id": 453, "evidence": "Risk Curation delegates to bd_platform.defi_yield_intelligence_layer.risk_curation_453"},
    721: {"canonical_capability_id": 454, "evidence": "Capital Protection Controls delegates to bd_platform.defi_yield_intelligence_layer.capital_protection_controls_454"},
    722: {"canonical_capability_id": 455, "evidence": "Stress Testing delegates to bd_platform.defi_yield_intelligence_layer.stress_testing_455"},
    723: {"canonical_capability_id": 456, "evidence": "Cross-Protocol Contagion delegates to bd_platform.defi_yield_intelligence_layer.cross_protocol_contagion_456"},
    724: {"canonical_capability_id": 457, "evidence": "Protocol Risk Passport delegates to bd_platform.defi_yield_intelligence_layer.protocol_risk_passport_457"},
    725: {"canonical_capability_id": 458, "evidence": "Risk-to-Decision Intelligence delegates to bd_platform.heroes_capability_layer.metric_methodology_registry_458"},
    726: {"canonical_capability_id": 459, "evidence": "Network Data Pro Metrics delegates to bd_platform.defi_yield_intelligence_layer.network_data_pro_metrics_459"},
    727: {"canonical_capability_id": 460, "evidence": "Atlas Blockchain Search delegates to bd_platform.defi_yield_intelligence_layer.atlas_blockchain_search_460"},
    728: {"canonical_capability_id": 461, "evidence": "Address/Balance Search delegates to bd_platform.defi_yield_intelligence_layer.address_balance_search_461"},
    729: {"canonical_capability_id": 462, "evidence": "Transaction Search delegates to bd_platform.defi_yield_intelligence_layer.transaction_search_462"},
    730: {"canonical_capability_id": 463, "evidence": "Block Search delegates to bd_platform.defi_yield_intelligence_layer.block_search_463"},
    731: {"canonical_capability_id": 464, "evidence": "Balance Updates delegates to bd_platform.defi_yield_intelligence_layer.balance_updates_464"},
    732: {"canonical_capability_id": 465, "evidence": "Stablecoin Network Metrics delegates to bd_platform.defi_yield_intelligence_layer.stablecoin_network_metrics_465"},
    733: {"canonical_capability_id": 466, "evidence": "Market Data Feed delegates to bd_platform.defi_yield_intelligence_layer.market_data_feed_466"},
    734: {"canonical_capability_id": 467, "evidence": "Market Data Pro delegates to bd_platform.defi_yield_intelligence_layer.market_data_pro_467"},
    735: {"canonical_capability_id": 468, "evidence": "Reference Rates delegates to bd_platform.defi_yield_intelligence_layer.reference_rates_468"},
    736: {"canonical_capability_id": 469, "evidence": "Indexes delegates to bd_platform.defi_yield_intelligence_layer.indexes_469"},
    737: {"canonical_capability_id": 470, "evidence": "Realized Metrics delegates to bd_platform.defi_yield_intelligence_layer.realized_metrics_470"},
    738: {"canonical_capability_id": 471, "evidence": "Supply Metrics delegates to bd_platform.defi_yield_intelligence_layer.supply_metrics_471"},
    739: {"canonical_capability_id": 472, "evidence": "Mining/Validator Metrics delegates to bd_platform.defi_yield_intelligence_layer.mining_validator_metrics_472"},
    740: {"canonical_capability_id": 473, "evidence": "Fee Metrics delegates to bd_platform.defi_yield_intelligence_layer.fee_metrics_473"},
    741: {"canonical_capability_id": 474, "evidence": "Activity Metrics delegates to bd_platform.defi_yield_intelligence_layer.activity_metrics_474"},
    742: {"canonical_capability_id": 475, "evidence": "Custom Metric Workbench delegates to bd_platform.defi_yield_intelligence_layer.custom_metric_workbench_475"},
    743: {"canonical_capability_id": 476, "evidence": "Community Charts/API delegates to bd_platform.defi_yield_intelligence_layer.community_charts_api_476"},
    744: {"canonical_capability_id": 477, "evidence": "Market + Network Join delegates to bd_platform.defi_yield_intelligence_layer.market_network_join_477"},
    745: {"canonical_capability_id": 478, "evidence": "Data Quality Methodologies delegates to bd_platform.defi_yield_intelligence_layer.data_quality_methodologies_478"},
    746: {"canonical_capability_id": 479, "evidence": "Historical Research Dataset delegates to bd_platform.defi_yield_intelligence_layer.historical_research_dataset_479"},
    747: {"canonical_capability_id": 480, "evidence": "Institutional APIs delegates to bd_platform.defi_yield_intelligence_layer.institutional_apis_480"},
    748: {"canonical_capability_id": 481, "evidence": "Cross-Network Decision Intelligence delegates to bd_platform.defi_yield_intelligence_layer.cross_network_decision_intelligence_481"},
    749: {"canonical_capability_id": 482, "evidence": "Institutional Trade Data delegates to bd_platform.defi_yield_intelligence_layer.institutional_trade_data_482"},
    750: {"canonical_capability_id": 483, "evidence": "Order Book Data delegates to bd_platform.defi_yield_intelligence_layer.order_book_data_483"},
}

def verify_prebuild_classification() -> dict[str, Any]:
    ids = sorted(PREBUILD_CLASSIFICATION)
    return {
        "ok": len(ids) == 50 and len(set(ids)) == 50,
        "count": len(ids),
        "unique": len(set(ids)),
    }
