name: blackdark
version: 1.0.0
config-version: 2
profile: blackdark
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
clean-targets: ["target", "dbt_packages"]

models:
  blackdark:
    staging:
      +materialized: view
    marts:
      +materialized: table
