#!/usr/bin/env python3
"""Bootstrap FREE human-ops secrets (no paid services required).

Writes gitignored `.env.softlaunch.local` (mode 0600) with:
  Soft Launch flags, vault/session/admin secrets, Admin TOTP, demo key off.

Does NOT print secret values. Does NOT require Stripe/Lemon/WhatsApp/domain purchase.
Does NOT require pyotp (stdlib only for TOTP secret/URI).
"""

from __future__ import annotations

import argparse
import base64
import secrets
import sys
from pathlib import Path
from urllib.parse import quote

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
from _secret_io import write_private_text

OUT = ROOT / ".env.softlaunch.local"


def _hex(n: int) -> str:
    return secrets.token_hex(n)


def _totp_secret() -> str:
    """Base32 TOTP secret without pyotp."""
    return base64.b32encode(secrets.token_bytes(20)).decode("ascii").rstrip("=")


def _totp_uri(secret: str, admin_email: str) -> str:
    label = quote(f"BLACKDARK Admin:{admin_email}", safe="")
    issuer = quote("BLACKDARK Admin", safe="")
    return (
        f"otpauth://totp/{label}?secret={secret}"
        f"&issuer={issuer}&algorithm=SHA1&digits=6&period=30"
    )


def _parse_existing(path: Path) -> dict[str, str]:
    if not path.is_file() or path.stat().st_size < 100:
        return {}
    out: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        raw = line.strip()
        if not raw or raw.startswith("#") or "=" not in raw:
            continue
        k, _, v = raw.partition("=")
        out[k.strip()] = v.strip()
    # Empty/whitespace-only Notepad residue counts as missing.
    return out or {}


def build_block(*, admin_email: str, rotate: bool) -> dict[str, str]:
    prev = {} if rotate else _parse_existing(OUT)
    return {
        "ENV": "production",
        "SOFT_LAUNCH": "true",
        "SERVICE_MODE": "web",
        "APP_BASE_URL": prev.get("APP_BASE_URL") or "http://127.0.0.1:8080",
        "ALLOWED_HOSTS": prev.get("ALLOWED_HOSTS") or "127.0.0.1,localhost",
        "CORS_ALLOWED_ORIGINS": prev.get("CORS_ALLOWED_ORIGINS")
        or "http://127.0.0.1:8080,http://localhost:8080",
        "SECRETS_MASTER_KEY": prev.get("SECRETS_MASTER_KEY") or _hex(32),
        "SESSION_TOKEN_PEPPER": prev.get("SESSION_TOKEN_PEPPER") or _hex(16),
        "ADMIN_API_KEY": prev.get("ADMIN_API_KEY") or _hex(24),
        "ADMIN_EMAILS": prev.get("ADMIN_EMAILS") or admin_email,
        "ADMIN_MFA_REQUIRED": "true",
        "ADMIN_TOTP_SECRET": prev.get("ADMIN_TOTP_SECRET") or _totp_secret(),
        "EXPOSE_B2B_DEMO_KEY": "false",
        "BLACKDARK_B2B_DEMO_KEY": "disabled",
        "LIVE_EXECUTION_ALLOW_API": "false",
        "JUPITER_LIVE_EXECUTION": "false",
        "PRODUCTION_GUARD_FAIL_CLOSED": "true",
        "UPTIME_SELF_PROBE_ENABLED": "true",
        "PRICE_FEED_WS_ONLY": "false",
        "LAUNCH_SKIP_EMAIL": "true",
        "LAUNCH_SKIP_TELEGRAM": "true",
        "EXTERNAL_UPTIME_CONFIGURED": prev.get("EXTERNAL_UPTIME_CONFIGURED") or "false",
        "BACKUP_SCHEDULE_CONFIGURED": prev.get("BACKUP_SCHEDULE_CONFIGURED") or "false",
        "CDN_WAF_ACTIVE": prev.get("CDN_WAF_ACTIVE") or "false",
    }


def write_softlaunch_env(*, admin_email: str, rotate: bool = False) -> dict:
    """Write `.env.softlaunch.local` in-process (no OS command / argv taint sink)."""
    email = (admin_email or "").strip().lower()
    force_rotate = bool(rotate)
    if OUT.is_file() and OUT.stat().st_size < 100:
        force_rotate = True
    block = build_block(admin_email=email, rotate=force_rotate)
    lines = [
        "# BLACKDARK Soft Launch — FREE human-ops bootstrap",
        "# Generated by scripts/bootstrap_free_human_ops.py",
        "# DO NOT COMMIT · mode 0600 · paste into Railway/host Variables",
        "# Paid later (not required for this file): Lemon/Stripe, WhatsApp Cloud, custom domain DNS",
        "",
    ]
    for k, v in block.items():
        lines.append(f"{k}={v}")
    lines.append("")
    uri = _totp_uri(block["ADMIN_TOTP_SECRET"], block["ADMIN_EMAILS"])
    lines.extend(
        [
            "# --- Admin MFA (Authenticator app) ---",
            "# otpauth URI: add in Google/Microsoft Authenticator (manual entry or URI)",
            f"# ADMIN_TOTP_URI={uri}",
            "",
        ]
    )
    write_private_text(OUT, "\n".join(lines) + "\n")
    size = OUT.stat().st_size
    if size < 100:
        return {"ok": False, "error": "wrote_suspiciously_small_file", "bytes": size, "path": str(OUT)}
    return {
        "ok": True,
        "wrote": str(OUT),
        "bytes": size,
        "mode": "0600",
        "soft_launch": True,
        "admin_email": block["ADMIN_EMAILS"],
        "keys_set": sorted(block.keys()),
        "next": [
            "Open .env.softlaunch.local locally (do not commit)",
            "Scan/add ADMIN_TOTP into Authenticator (URI comment in file)",
            "Follow docs/FREE_HUMAN_OPS_PLAYBOOK_AR.md",
        ],
        "secrets_printed": False,
    }


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--admin-email", default="mopayment1@gmail.com")
    p.add_argument("--rotate", action="store_true")
    args = p.parse_args()
    result = write_softlaunch_env(admin_email=args.admin_email, rotate=args.rotate)
    print(result)
    return 0 if result.get("ok") else 2


if __name__ == "__main__":
    raise SystemExit(main())
