#!/usr/bin/env python3
"""Bootstrap FREE human-ops secrets (no paid services required).

Writes gitignored `.env.softlaunch.local` (mode 0600) with:
  Soft Launch flags, vault/session/admin secrets, Admin TOTP, demo key off.

Does NOT print secret values. Does NOT require Stripe/Lemon/WhatsApp/domain purchase.
"""

from __future__ import annotations

import argparse
import secrets
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
from _secret_io import write_private_text  # noqa: E402

OUT = ROOT / ".env.softlaunch.local"


def _hex(n: int) -> str:
    return secrets.token_hex(n)


def _totp_secret() -> str:
    import pyotp

    return pyotp.random_base32()


def _parse_existing(path: Path) -> dict[str, str]:
    if not path.is_file():
        return {}
    out: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        raw = line.strip()
        if not raw or raw.startswith("#") or "=" not in raw:
            continue
        k, _, v = raw.partition("=")
        out[k.strip()] = v.strip()
    return out


def build_block(*, admin_email: str, rotate: bool) -> dict[str, str]:
    prev = {} if rotate else _parse_existing(OUT)
    return {
        "ENV": "production",
        "SOFT_LAUNCH": "true",
        "SERVICE_MODE": "web",
        "APP_BASE_URL": prev.get("APP_BASE_URL") or "http://127.0.0.1:8080",
        "ALLOWED_HOSTS": prev.get("ALLOWED_HOSTS") or "127.0.0.1,localhost",
        "CORS_ALLOWED_ORIGINS": prev.get("CORS_ALLOWED_ORIGINS") or "http://127.0.0.1:8080,http://localhost:8080",
        "SECRETS_MASTER_KEY": prev.get("SECRETS_MASTER_KEY") or _hex(32),
        "SESSION_TOKEN_PEPPER": prev.get("SESSION_TOKEN_PEPPER") or _hex(16),
        "ADMIN_API_KEY": prev.get("ADMIN_API_KEY") or _hex(24),
        "ADMIN_EMAILS": prev.get("ADMIN_EMAILS") or admin_email,
        "ADMIN_MFA_REQUIRED": "true",
        "ADMIN_TOTP_SECRET": prev.get("ADMIN_TOTP_SECRET") or _totp_secret(),
        "EXPOSE_B2B_DEMO_KEY": "false",
        "BLACKDARK_B2B_DEMO_KEY": "disabled",
        "LIVE_EXECUTION_ALLOW_API": "false",
        "JUPITER_LIVE_EXECUTION": "false",
        "PRODUCTION_GUARD_FAIL_CLOSED": "true",
        "UPTIME_SELF_PROBE_ENABLED": "true",
        "PRICE_FEED_WS_ONLY": "false",
        "LAUNCH_SKIP_EMAIL": "true",
        "LAUNCH_SKIP_TELEGRAM": "true",
        "EXTERNAL_UPTIME_CONFIGURED": prev.get("EXTERNAL_UPTIME_CONFIGURED") or "false",
        "BACKUP_SCHEDULE_CONFIGURED": prev.get("BACKUP_SCHEDULE_CONFIGURED") or "false",
        "CDN_WAF_ACTIVE": prev.get("CDN_WAF_ACTIVE") or "false",
    }


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--admin-email", default="mopayment1@gmail.com")
    p.add_argument("--rotate", action="store_true")
    args = p.parse_args()
    block = build_block(admin_email=args.admin_email.strip().lower(), rotate=args.rotate)
    lines = [
        "# BLACKDARK Soft Launch — FREE human-ops bootstrap",
        "# Generated by scripts/bootstrap_free_human_ops.py",
        "# DO NOT COMMIT · mode 0600 · paste into Railway/host Variables",
        "# Paid later (not required for this file): Lemon/Stripe, WhatsApp Cloud, custom domain DNS",
        "",
    ]
    for k, v in block.items():
        lines.append(f"{k}={v}")
    lines.append("")
    # TOTP URI helper (no secret reprint beyond file)
    try:
        import pyotp

        uri = pyotp.TOTP(block["ADMIN_TOTP_SECRET"]).provisioning_uri(
            name=block["ADMIN_EMAILS"],
            issuer_name="BLACKDARK Admin",
        )
        lines.extend(
            [
                "# --- Admin MFA (Authenticator app) ---",
                f"# otpauth URI (also in file comment only): scan via Authenticator",
                f"# ADMIN_TOTP_URI={uri}",
                "",
            ]
        )
    except Exception:
        pass
    write_private_text(OUT, "\n".join(lines) + "\n")
    print(
        {
            "ok": True,
            "wrote": str(OUT),
            "mode": "0600",
            "soft_launch": True,
            "admin_email": block["ADMIN_EMAILS"],
            "keys_set": sorted(block.keys()),
            "next": [
                "Open .env.softlaunch.local locally (do not commit)",
                "Scan ADMIN_TOTP into Authenticator (URI comment in file)",
                "Follow docs/FREE_HUMAN_OPS_PLAYBOOK_AR.md",
            ],
            "secrets_printed": False,
        }
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
