#!/usr/bin/env python3
"""Generate production launch secrets and optional .env.launch.local (gitignored)."""

from __future__ import annotations

import argparse
import re
import secrets
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_LEMON = (
    "https://blackdark.lemonsqueezy.com/checkout/buy/d044fb7a-5722-498a-885b-dfd04fb7ed05"
)


def _hex(nbytes: int) -> str:
    return secrets.token_hex(nbytes)


def _parse_env_file(path: Path) -> dict[str, str]:
    if not path.is_file():
        return {}
    out: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        raw = line.strip()
        if not raw or raw.startswith("#") or "=" not in raw:
            continue
        key, _, value = raw.partition("=")
        key = key.strip()
        value = value.strip()
        if key:
            out[key] = value
    return out


def _lemon_from_example() -> str:
    example = ROOT / ".env.production.example"
    parsed = _parse_env_file(example)
    return parsed.get("LEMON_SQUEEZY_CHECKOUT_PRO") or DEFAULT_LEMON


def build_env_block(
    *,
    app_base_url: str,
    admin_email: str,
    existing: dict[str, str] | None = None,
) -> dict[str, str]:
    prev = existing or {}
    return {
        "ENV": prev.get("ENV") or "production",
        "SERVICE_MODE": prev.get("SERVICE_MODE") or "web",
        "APP_BASE_URL": (prev.get("APP_BASE_URL") or app_base_url).rstrip("/"),
        "SECRETS_MASTER_KEY": prev.get("SECRETS_MASTER_KEY") or _hex(32),
        "SESSION_TOKEN_PEPPER": prev.get("SESSION_TOKEN_PEPPER") or _hex(16),
        "ADMIN_API_KEY": prev.get("ADMIN_API_KEY") or _hex(24),
        "ADMIN_EMAILS": prev.get("ADMIN_EMAILS") or admin_email,
        "LEMON_SQUEEZY_CHECKOUT_PRO": prev.get("LEMON_SQUEEZY_CHECKOUT_PRO") or _lemon_from_example(),
        "BLACKDARK_B2B_DEMO_KEY": prev.get("BLACKDARK_B2B_DEMO_KEY") or "disabled",
        "PRICE_FEED_WS_ONLY": prev.get("PRICE_FEED_WS_ONLY") or "false",
        "UPTIME_SELF_PROBE_ENABLED": prev.get("UPTIME_SELF_PROBE_ENABLED") or "true",
        "PRODUCTION_GUARD_FAIL_CLOSED": prev.get("PRODUCTION_GUARD_FAIL_CLOSED") or "true",
        "LAUNCH_SKIP_EMAIL": prev.get("LAUNCH_SKIP_EMAIL") or "true",
    }


def render_env(block: dict[str, str]) -> str:
    lines = [
        "# BLACKDARK launch secrets — paste into Railway Variables",
        "# Generated by scripts/generate_launch_secrets.py",
        "# DO NOT COMMIT",
        "",
    ]
    for key, value in block.items():
        lines.append(f"{key}={value}")
    lines.extend(
        [
            "",
            "# Still set manually on Railway:",
            "# DATABASE_URL=postgresql://...   (Postgres plugin)",
            "# REDIS_URL=redis://...           (recommended)",
            "# TELEGRAM_BOT_TOKEN=...",
            "# TELEGRAM_CHAT_ID=...",
            "# LEMON_SQUEEZY_CHECKOUT_WHALE=... (optional)",
            "# SENTRY_DSN=...                  (optional)",
        ]
    )
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate BLACKDARK launch secrets")
    parser.add_argument(
        "--write",
        action="store_true",
        help="Write secrets to .env.launch.local (gitignored)",
    )
    parser.add_argument(
        "--app-base-url",
        default="https://blackdark-production.up.railway.app",
    )
    parser.add_argument("--admin-email", default="mopayment1@gmail.com")
    parser.add_argument(
        "--rotate",
        action="store_true",
        help="Force new secrets even if .env.launch.local exists",
    )
    args = parser.parse_args()

    path = ROOT / ".env.launch.local"
    existing = {} if args.rotate else _parse_env_file(path)
    block = build_env_block(
        app_base_url=args.app_base_url,
        admin_email=args.admin_email,
        existing=existing,
    )
    text = render_env(block)
    print(text)

    if args.write:
        path.write_text(text, encoding="utf-8")
        print(f"Wrote {path}")
        # Validate lemon URL shape
        lemon = block.get("LEMON_SQUEEZY_CHECKOUT_PRO", "")
        if not re.match(r"^https://.+/checkout/", lemon):
            print("WARN: Lemon checkout URL looks unexpected — verify in Lemon dashboard")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
