#!/usr/bin/env python3
"""Generate production launch secrets and optional .env.launch.local (gitignored)."""

from __future__ import annotations

import argparse
import secrets
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def _hex(nbytes: int) -> str:
    return secrets.token_hex(nbytes)


def build_env_block(*, app_base_url: str, admin_email: str) -> dict[str, str]:
    return {
        "ENV": "production",
        "SERVICE_MODE": "web",
        "APP_BASE_URL": app_base_url.rstrip("/"),
        "SECRETS_MASTER_KEY": _hex(32),
        "SESSION_TOKEN_PEPPER": _hex(16),
        "ADMIN_API_KEY": _hex(24),
        "ADMIN_EMAILS": admin_email,
        "BLACKDARK_B2B_DEMO_KEY": "disabled",
        "PRICE_FEED_WS_ONLY": "false",
        "UPTIME_SELF_PROBE_ENABLED": "true",
        "PRODUCTION_GUARD_FAIL_CLOSED": "true",
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate BLACKDARK launch secrets")
    parser.add_argument(
        "--write",
        action="store_true",
        help="Write secrets to .env.launch.local (gitignored)",
    )
    parser.add_argument(
        "--app-base-url",
        default="https://blackdark-production.up.railway.app",
    )
    parser.add_argument("--admin-email", default="mopayment1@gmail.com")
    args = parser.parse_args()

    block = build_env_block(app_base_url=args.app_base_url, admin_email=args.admin_email)
    lines = [
        "# BLACKDARK launch secrets — paste into Railway Variables",
        "# Generated by scripts/generate_launch_secrets.py",
        "# DO NOT COMMIT",
        "",
    ]
    for key, value in block.items():
        lines.append(f"{key}={value}")
    lines.extend(
        [
            "",
            "# Still set manually:",
            "# DATABASE_URL=postgresql://...",
            "# LEMON_SQUEEZY_CHECKOUT_PRO=https://...  (or Stripe keys)",
            "# REDIS_URL=redis://...  (recommended)",
            "# TELEGRAM_BOT_TOKEN=...",
            "# TELEGRAM_CHAT_ID=...",
        ]
    )
    text = "\n".join(lines) + "\n"
    print(text)

    if args.write:
        path = ROOT / ".env.launch.local"
        path.write_text(text, encoding="utf-8")
        print(f"Wrote {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
